export const SALESFORCE = 'salesforce'
export const CUSTOM_FIELD = 'CustomField'
export const CUSTOM_OBJECT = 'CustomObject'
export const METADATA_OBJECT_NAME_FIELD = 'fullName'
export const FORMULA_TYPE_PREFIX = 'formula_'
export const PROFILE_METADATA_TYPE = 'Profile'
export const SETTINGS_METADATA_TYPE = 'Settings'

// Anotations
export const LABEL = 'label'
export const RESTRICTED_PICKLIST = 'restricted_pick_list'
export const PICKLIST_VALUES = 'values'
export const API_NAME = 'api_name'
export const FIELD_LEVEL_SECURITY = 'field_level_security'
export const FORMULA = 'formula'
