/*
 *                      Copyright 2024 Salto Labs Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export const simpleReportDefinition =
  'H4sIAAAAAAAA/+1dW3ObShJ+P1XnP6g4+7Bb6+hiJ7bXJTuFYCSz5qJwseN9oYiEE06Q0AJKopza/749XCSujgWDLwmpVGIPQ3/TPT093T3DzPDtt4Xd+WK6nuUsz6lBt091zOXMmVvLj+eUpo5fnVJvL37/bbj0PGd2ppiuZdjWd3MuffjTnPmMs/QNa2m6HSCz9M6CWufUJ99fnfV6X79+7S5N31tbvtmdOYueN/tkLgyvF1SjOmtrfk6pisrK14eHb05Oj/tnsrlyXJ8176yl5UOTzhhNUSVBRlNJVvWj/qmuRlX1k9OTs8Hx8b8G/ZPT18dvjo6pHR/97oDq+NbC9HxjsQK+UvWAn04n4mhhrFbQ/NSbF9BW3HDbnH803S7U6LpBu0Ao3fm2bV0vlobbDcl0s80XguJhL4mVRN8RC0qhPEshKocnc9ObudbKd9xtGZS65sxx5+pmZXZmtuF551RIQd6WUxeR9Fg05kRO5SRRR6Iq3w57u5eTJL8Y9tr0EiVQdo3LOneWaQfVY5RxXECFz86pK3SrR3gcS+E2ff9+TllLn7qA3hv2AkI1aCuMzE1TtD3fhX6hLu7VlPrAU5q5oieI6vQqEhlziGd1IEVYKiFdRmJRTiTvNI65irqDBAiLQvGDCuWwfBhr8EPHWfsd/5PldcIhQwJWpIU8b8onw3YWKqB2xg4osgE/KOvFwnA3JDAlmZtwIs3rKqfyj44+RbKgq7fTPDDuTF0Z0/UVeoxoVZMLWKtLfMzTE8wBJ7GKTvO8dIN2o/WD49imsQR9cdcmARyWU6Y8fVssLEUTBBobutowkoh0llZRno87w/ZIMDKVOdxWXdJUJOv/ljixOazQVOpC0maQ7hiGVi71Ea1wSnN8KJfSjf4fJEsFGITYABvAqNx1Qx0fDPZrJCtJizp31h9smLZPu32CA1FqUJ80BeljTmHAXN4iWtZlWpw0OFQwnEq/j1lrBAhbSPCSOBWm67m5MpdzcIs3V+YGv4K9JviR3XpkZyc521PT5djpN8+JVw0OIW2KvQMFHAhRkXj4faRwLAeWqIkhhaUKbqiuSpMJX9uXCqkUm35RUi85cUJifEYwmszXaDCWNT0eI0ZFrD66BXFPGjKMkac2lRFDB86+jGgFj/56bcdWEEYD2BG+QDUIjThaYzkkMig35uj13IJfzMSQG1TnKIBiGKQoeyEephGHvUykNOwVxGhDCCZXztJc+smQaujnIjZkmwuolQrZGEmYgushqrpAT4c9/wGRWmidUmVQujJcoB0DMo5tQ/QO4SUFbvqd6WJGz6lutxf8zQp2vzAz1eZ7I80yHvbvzC1mOrZ687pIJStov4LAPLLYPWM5YQ/trzJ0GZ5WlJw9uy8lsTANb+2aXZFXDNv04oBECIuL25VT3rCwQHtajUpq1C+hUHMLLBHOh8UqBY/YuKyePhUYzQIDOQwYqGAwA46VF2Ip48wNrwmiPpZkgVZfsl6HzhI9KkiXAMMArpACoXmOzmu0cg3lLE4WkWNGniA15inb1fvTgz5G3EQMk4C1yIWpDwGJqcixGfuhiZyadrIDlXk1IGQLZYnntenDw40qPODcDYw3HudWOJFF79O8FAbaVXDw8KJlDvztSGK1e5meTvlbrDk3tMxCRNOsnGheDWWloIkQWInaDAgQfiTzjKSVVEHvdFETRkhO9ykJ9QxkwtMjxOetDZ4XO/AmKRgRTWKo+pYmCFYzLe7BJI8n24Wz7MEUZ/mb6L/u0n5rzc//wtP8QVh0sPxsbg6+HXz7HzErIvPFkTqLZO4asYSMCavRfDSlNmcWo7wag11SVVJp/nGgOBHMS3MDKYWF3k9hcmkYTNZEEUyaPmpagkEiTQKOHg+NHikwQ4/HjwA1ZdTHgNJGj6Hs0YJOs9NctDBEwgmTpanOIoYTmhfMNU4cqpeSptBiwYoaSTA8GXE4ddggznbWA789Cn9yk8PScRekoCayhN3M+pMreHjYRBKjF0eAoXtKjGyJSH3zW+GqfFUIjaepzn/Xjm+ONqKxAAzGWX7BbgTeT4NHLdUxvZmxMpWgBR539w5qBxuMAlUixSs0BA8Q8AeftD14+AR2ciedh5uyl5SWe07pCxKJ3mT+or5GFucoIpUIqhy2aYqfIU1BlIkny1Pkd84QEtvPm78g0+6y9AUx61CcvhiDY7W2jReTvJi556+O2lxEm4tocxFtLqLNRbS5iDYX8RPkImZrF4ekhXvmq8IQyEdkWvmXh9d67qJtNQffDlYQS381rY+ffHNuLPxgneSfD6pFmFFC+Y4sv0fAzRGJtra5kDYXUpoLmcpofIO4yaWKWFoo/ECpWqvbbEibDamXDWl3bTxR1oNYiF+a9Qi/1aMXzhqmhr/fRPPzP9pESJsIaRMhbSLk50mEEJpgHj8PkjFFHXJrEW2CpF4X/SBBEsRbbYakGtmXlSFpd2xscap/+BLgJwpmruXjI2WSb/m57EPhd4IyB8rI0Q/98AXTYUK0xBEz0eO6aZPCg2oKaWcakgco7NhAbLniHxHffcf5MJj98j9RB0AAGZ+RIsn3JIDKumb7jEiChcUxYZnhqAJTmlOpRuz+PE0Vmj/I1VQhCR5D8Qd0I6TeICSSki+P2JJQjFgnlgXdpXmUKvLaO/G0J0h4KAf0tKQm+HiQR1oBKToppQztXu+qAtw1J6s4Vg5E2SRz4VFal4jVyA2+BzpGVUjvjGpueGRXXeZuQGlu+CZecSGpdYp+ybEs2jeHUeIjhA+KJ7PEoQHx1OOZPlVEOpRDML6iH/MghUcQhI9KJ+toeorhbcsrwC9eeAmeVJo8IbjQ0CPOm1UTzPthPYrdDUSXO8VibNng/gSkEgdZ5EbJH6qQG1hqadR9r0KXaESrKXU0hdTkSUBTBoNef9A77B8ebpuYPkog/MKwu/YtuyvyLLxHXeDqrwaDV/1Bp39y1u/D326/o6lMq2LPRcVK95s+iYod9auq2FG/0z9tRsVKQ/3ycLqNtX+RWPtqd3BaG3HXI1kacYciZi45npWRKI0bD70VxCOmdGPKfjCPMrW3wXcNuDb4rhl8+66xtK2lefDZW3/wrLlluJs2Bo9A2hj8Wbq9TxaDlw2WP4I7GKImxkcBD4qPAo4VqGE3tujMtuxS1dCDlysc2Kbgf3hOUV/ImW3KdrfvE+zvjc0uuS2+xc5sZuf6s9tP/Gy3+O5tZfbdVgJTMRIb3VAa7SrafwddjYXwtO0Yrq3pdtymTMoe41TjdLy/HMn4cF+lkatOprRMCwhPWw2fdb8DUun3BVjb3a2kYJo9Vz+Do4A284B1w3Miahjw3tsi5oZf+D10FSBOZPRrBW/YbFgjJjI9vdRVaZqJKvvwpzDqqwJyg0Y6hGJ7HeJXBaf5Q8YTWPhiEszZOw0VHXbfQC8d7bM/r/J4YjQZGz0IMW+FkbTHxtAqiKDgtMjqPLpO7LaPNTAPUmD7i4390DY2zrqKQznmRFpkOIjjYaBLmpo9DHjYy5Ie4mvJ5mvbrOK+RmF8HiVPFLupxsIEv7kC0FbkDzzcWDBWpL3kz+YmfjnoVyqpKukEfXwzmhHck7Zw5qbdDffuhTei/S3wu0IrHLtOqoz3gUchVMXdgOHTjF03ZjP8sQf8rMMY+KyHWyp93ZoPe8BToe/+IhkdRMMr44FlVaHVjXLd+DV1osAs52xVnCDIXE0Y322Yuclwe79hlAmxtsSzTzYdP5prcrfqRDdElty3gx/1d+mwYUG1rJm9CG/0yVtQ3OUn6Z6PI5cigjumYyZ+wFz+MpGIt+J7TfCTQYK1fK1s4wdZtQ35jW83yXNs2Lbs4NkpckC2v6froMXKdjZmqt6uLF2XWXu+s8Aas6u7K0vXvQb5OKmacUm63tRw/WWa5LZo11Ol8mm0ow7Djjrcq6MOSzoqfRtN218P7K/C3GrUZfvsfcL1jxIdWfhuktdwzaBgu2F2MSGcO4LdVGlDPOzdB/Ikkkju7cHvvW5SIjuwlyGZ7ZYU/N6bhiUTgT07ydy/aoHfO95fMuXrhmUCwsshBCSTKw7dlLi49LZrqPP7b/8HRhOOPjt7AAA='
export const simpleReportDefinitionResult = {
  components: [
    {
      KEY_COMPONENT: 54,
      FLAG_SECONDARY_DIM: false,
      FIELD_CLASS: 'com.netledger.app.reporting.measure.NLSalesForecastMeasure',
    },
    {
      KEY_COMPONENT: 5,
      FLAG_SECONDARY_DIM: false,
      FIELD_CLASS: 'com.netledger.app.reporting.dimension.NLSalesrepDimension',
    },
  ],
  parameters: { accounting_book_current_id: '1', accounting_book_id: '1' },
  sorts: [
    { KEY_COMPONENT: '54', FIELD_ALIAS: 'prefweightedamt', SEQ_NUMBER: 0, FLAG_DESCENDING: true, FLAG_SUBTOTAL: false },
  ],
  fields: [
    {
      KEY_COMPONENT: 5,
      FIELD_TABLE: 'REPKEYS',
      FIELD_ALIAS: 'SVALIDNAME',
      FLAG_DIMENSION: false,
      FIELD_UNIT_TYPE: -1,
      FLAG_ROLLUP: true,
      FIELD_DATE_FILTER_INDEX: 0,
      FLAG_APPLY_FORWARDING: true,
      FLAG_MEASURE: false,
      SEQ_NUMBER: 1,
      FIELD_LABEL: 'Sales Rep',
      FIELD_URL: '/app/common/entity/entity.nl?id={srep,entity,nkey,x,x}',
      FIELD_URL_TYPE: 'DERIVED',
      FLAG_DUAL_COLUMN: false,
      FLAG_PERCENT_TOTAL: false,
      FLAG_PERCENT_INCOME: false,
      FLAG_PERCENT_EXPENSE: false,
      FLAG_RUNNING_BAL: false,
      FLAG_SHOW_OPENING_BAL: false,
      FLAG_SHOW_ABS_DIFF: false,
      FLAG_SHOW_PCT_DIFF: false,
      FLAG_SUB_TOTAL: false,
      FLAG_DISPLAY: true,
      FLAG_DROP_DECIMAL: false,
      FLAG_DIV_BY_THOUSAND: false,
      FLAG_NEG_IN_RED: false,
      FIELD_NEG_VAL_FORMAT: 'norm',
      FIELD_FORMAT: 'text',
      FLAG_TOTAL_FORMULA: true,
    },
    {
      KEY_COMPONENT: 54,
      FIELD_ALIAS: 'FORMULAFIELD2',
      FLAG_DIMENSION: false,
      FIELD_UNIT_TYPE: -1,
      FLAG_ROLLUP: false,
      FIELD_COMPARISON_TYPE: 'SUM',
      FIELD_DATE_FILTER_INDEX: 0,
      FLAG_APPLY_FORWARDING: true,
      FLAG_MEASURE: true,
      SEQ_NUMBER: 2,
      FIELD_LABEL: 'Formula',
      FIELD_URL: 'cr=-3',
      FIELD_URL_TYPE: 'DERIVED',
      FLAG_DUAL_COLUMN: false,
      FLAG_PERCENT_TOTAL: false,
      FLAG_PERCENT_INCOME: false,
      FLAG_PERCENT_EXPENSE: false,
      FLAG_RUNNING_BAL: false,
      FLAG_SHOW_OPENING_BAL: false,
      FLAG_SHOW_ABS_DIFF: false,
      FLAG_SHOW_PCT_DIFF: false,
      FLAG_SUB_TOTAL: false,
      FLAG_DISPLAY: true,
      FLAG_DROP_DECIMAL: false,
      FLAG_DIV_BY_THOUSAND: false,
      FLAG_NEG_IN_RED: false,
      FIELD_NEG_VAL_FORMAT: 'norm',
      FIELD_FORMAT: 'currency',
      FIELD_FORMULA: '{salesforecast,x,prefweightedamt,x,x}+{salesforecast,x,prefweightedamt,x,x}',
      FIELD_FORMULA_BY_SEQ: '{3}+{3}',
      FLAG_TOTAL_FORMULA: true,
    },
    {
      KEY_COMPONENT: 54,
      FIELD_ALIAS: 'PREFWEIGHTEDAMT',
      FLAG_DIMENSION: false,
      FIELD_UNIT_TYPE: -1,
      FLAG_ROLLUP: false,
      FIELD_DATE_FILTER_INDEX: 0,
      FLAG_APPLY_FORWARDING: true,
      FLAG_MEASURE: true,
      SEQ_NUMBER: 3,
      FIELD_LABEL: 'Forecast Amount (Weighted)',
      FIELD_URL: 'cr=-3',
      FIELD_URL_TYPE: 'DERIVED',
      FLAG_DUAL_COLUMN: false,
      FLAG_PERCENT_TOTAL: false,
      FLAG_PERCENT_INCOME: false,
      FLAG_PERCENT_EXPENSE: false,
      FLAG_RUNNING_BAL: false,
      FLAG_SHOW_OPENING_BAL: false,
      FLAG_SHOW_ABS_DIFF: false,
      FLAG_SHOW_PCT_DIFF: false,
      FLAG_SUB_TOTAL: true,
      FLAG_DISPLAY: true,
      FIELD_SUMMARY: ' SUM',
      FLAG_DROP_DECIMAL: false,
      FLAG_DIV_BY_THOUSAND: false,
      FLAG_NEG_IN_RED: false,
      FIELD_NEG_VAL_FORMAT: 'paren',
      FIELD_FORMAT: 'currency',
      FLAG_TOTAL_FORMULA: true,
    },
  ],
  uiPreferences: {
    PARAMETER_CASH_BASIS: false,
    PARAMETER_TAXCASH_BASIS: 'F',
    PARAMETER_SHOW_ZEROS: true,
    PARAMETER_SHOW_SINGLEROWLINES: true,
    PARAMETER_DISPLAY_TYPE: 'data',
    PARAMETER_INC_VS_EXP: false,
    PARAMETER_GRAPH_TOP: 100001,
    PARAMETER_WEB_STORE: false,
    PARAMETER_ACTIVITY_ONLY: false,
    PARAMETER_ALLOW_WEBQUERY: false,
    PARAMETER_GRAPH_3D: false,
    PARAMETER_SHOW_CURRENCY_SYMBOL: true,
    PARAMETER_EXPAND_LEVEL: 100,
  },
  criteria: [
    {
      descriptor: {
        FIELD_ALIAS: 'DDATE',
        FIELD_OP_CLASS: 'BETWEEN',
        FILED_TYPE: 'DATE',
        SEQ_NUMBER: 0,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: false,
        FLAG_VIRTUAL_FIELD: true,
        FIELD_DESCRIPTOR: 'salesforecast,x,dreportdate,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [{ FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: 'TM' }],
    },
    {
      descriptor: {
        FIELD_ALIAS: 'KSUBSIDIARY',
        FIELD_OP_CLASS: 'SUBSIDCHILDRENOF',
        FILED_TYPE: 'SELECT',
        SEQ_NUMBER: 1,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: false,
        FLAG_VIRTUAL_FIELD: true,
        FIELD_DESCRIPTOR: 'salesforecast,tranline,ksubsidiary,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [{ FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: 1 }],
    },
  ],
  flags: {
    KEY_REPORT_ID: 308,
    KEY_SCRIPT_ID: 'CUSTOMREPORT_308_T2257860_787',
    FIELD_KEY: 308,
    FIELD_CODE: 'QUICK_REPORT',
    FIELD_DESCRIPTION: 'testing out this report',
    FIELD_NAME: 'ShalomTest Forecast Summary',
    FIELD_ORIGINAL_TITLE: 'ShalomTest Forecast Summary',
    FIELD_PERM_TYPE: 'REPO_SFA',
    KEY_FEATURE: 'SFA',
    FLAG_PERIODS_ALLOWED: true,
    FLAG_DISPLAY_TYPE: 'SUMMARY',
    FLAG_ONE_DATE: false,
    FLAG_PRIMARY_OUTER_JOIN: false,
    FLAG_CUSTOM_MODE: true,
    FLAG_CASH_BASIS: false,
    FLAG_SHOW_ZEROS: true,
    FLAG_INACTIVE: false,
    FIELD_VERSION: 8,
    FLAG_PERIODS_ON: false,
    FLAG_USE_FISCAL_YEAR_RANGE: false,
    FLAG_USE_TAX_PERIODS: false,
    KEY_ENTITY: '7',
    FLAG_SHOW_LINK: false,
    FLAG_SUPPORTS_CONSOL_SUBSIDIARY: true,
    FIELD_TOGGLE_TYPE: 'NOTHING',
    FLAG_AFFECTED_BY_COGS: false,
    FLAG_ACTIVITY_ONLY: false,
  },
}
export const fullReportDefinition =
  'c08ae05683104eeb06cff13026bdc5e11098095ed29d0fe1be26357c1ae9fe5e@GZC@2022.2.14@H4sIAAAAAAAA/+1dbXObOhb+vjP3P3jcnf2U+q0vabNO72CQHW4xuIDT5n5hiK203NqQBXzbdGf/+0qAbWyEa4NI4+TMfRlHCB3p6JyjR4+A0/39+3xW+xv7geO55/V2o1WvYXfiTR3383l9bPafv6n//u63f3TdIPAmZwb2HXvm/MBT7fovPAlFzw1tx8V+jTTjBmdRrfP6lzC8PWs2v3371nBxGCycEDcm3rwZTL7guR00o2r12sKZntdNw5T0y07n1emb160zHd96fijhG8d1QtKlM3FsmNpQRyNNN60X7Y5lJlXpH2ft16/fvmm137zqnJ6+rK/H0Wq067XQmeMgtOe3ZFwb9ch4arVkRHP79pZ0f+POd6SvtOMzPP2M/Qap0fCjfhGlNKarvjWCpTb8RtxMY7v7w6i420zLSktfNxaVkvLtFpJycmWKg4nv3IaevyojpT6eeP7UvLvFtcnMDoLzetyCviqvv0u0J6G+rMqmrKkWUk39qttc35xu8m97tsBBqoSUXdKy2o2DZ1H1pZT+sqAeXzuvv0dXViJPluq0Tz9+nNcdN6y/IxPWbUYNlWjbEHV5tNF2EPpkXurvdlpKecEjQXwvDFC91izYSF9GimSRpjhrJW5X1CSUUQmZb0EVZUGxeoJCfiHLuEDItAxzaPIQKqF4OohJZWSHxPdqNzicfKn5WzbNQ7QqDLPjNb7YM29uUsl9x7XdCXFPxb7zFiEPkZouD4hCFcuUTeW+hY+QPrTMq1FWLrV4azXTRnlL7yPBHOtZQYIoamPVlNVByQEpwoCOR9YkwxIURfuI1t587XkzbLvEfvwF5iBHko2RIlyxVWeMh0OBBsLSYjQVWZJgosrGMdJl2lVLG5tIt/7QZLUyUXEgtYbpiMJdhmBckKBkyEZWxI09C3jIMC60j9afSNcYMjgNg3idaMqXDD3xGETk+JdIN9LxdeotrmdkUe+0Wm8aLY6eqFVnUWMDkQhliCR2XiFBt3RBHVSks6U4U/i0HFklgmigJChKNslyPsW32J0S2Hz3Ht/RWyiqIj+lFWI7O83EnlNeFq7I6vvKZs4YjyieMgi+UA1NIX/3DFmSSSSqQiRVKkGplqkNBqkVNsJJzzut1zz8KW6bvR5IyBRkhaOUsa5khDTJLqC52k8kv/yFS3ZRDXf2+8Q/p0P9F9m3/Jv+d+N787jOeXmoSKdU6PeRaCLJ6l2RWR1UExwTeDjSkShEOw4dCQaNMIXRc9R1GmyJy5FYpVRmgMJYkhHByhm/FhZTh/yBU27dLj6gSJQoIsM4SGJnU2K3ubVb6zYZ+8Qu2dDeei52w/S2rhtmdo1ohuek1sa2UdSGIwJvVNMaCqNuM9xjtxhHwI0yUnpr+6TtpUDRm83whG4H6mSDcIN9OtDzeqPRjP7dVuxhW92NPu/c7eaN4fDJXMnc2t+1mE5bwPoNRIKwREGgJA8PWNSKuK6oCIaRCV07eRGHWA7lUBqqsrX/kZaX2L3L2HBcyDAiMKwNw2o/CcOaYztY+DhtVsO4CMyJqzkxNxNPwZx6C1Iv5GJUjPWYsfZ2ozEUWIujQRtHsggviUllPFStvqYPBfO4F+EY2Qs9BvkX8W+9sfgemUwGrogkQZGFrG2rZJj8xqIPkLkc0vZcH94emWQkD9SY5C7VXEzdDZG6wX1UE0PGqmxu7gfjDSev5VXXFGU8qngQlHwkHqdQdlBWJfRpczA8YnvizsORoMtkL5eorPQ0C6ORckVN56OgS7I62H9fV8ypzFhXBhoMozhRegBDsrVN8+W8J9hAHyx1POwhvaI5VYQeUnj4v4oG/BqLuBMuzbDJHk7eLY0FJVnkqnPxhKcVKVI0NVNQ7keUrBJ3r86wN2ShTyMS7SsWpo9VlYQYehxaraCImdXIiO5PmtAzyJLZ79+DqJFo3oeoce8+jD05Iax4fU6OGnnAIl0bWRIS5WH1mrmkJLF5oY0NQWWc0fIURtcOmfLEFcpZLVKXJGbHO5LMsuB6/pyXqIGuUeBXfhEjkIvGSG7tLTdlMV7k1myOSgNMN5m8lEqFjBWhXvvPwgtx706150SK6Ll/k41t9AwXxYv1Gg4m9i02oj4E8s0HUjt6qC0yJl6jJR2hLkIg2i/tD3WgKFSutbM/iD4mwgw4hXKS2JyCoQsf+2NFAWoBqAWgFor7FlALQC0AtQDUAlALhUUBtQDUAlALQC3sSS2E+DsQC0AsALHwQIkFCo+BUgBKASiFgl4FlAJQCkApAKUAlEJhUUApAKUAlAJQCkApAKUAlMLRUwrJswr0AzDALDwGZoHnhhmIhSdHLPAwzzSxsB3Zlm8J1nTvG09UB9QDUA9APQD1cPzUA8+FCZgHYB6KNwTMAzAPwDwA81AZ80ACoiwB9QDUA1APxZ3r0VAP3ELbUVMPW73++fctO29frD5v6ePP4feT0LfdmePik6/2ZBKefCf/iBeyIhE0p/Xpn+f/vaHKmDrzk+jH9WLyFYfBSUDWLmf6Fd+1aa3/cYtHeVyIIQ9HCo/gD4wIMCLAiAAjAowIMCLAiAAjAozI02FEuJ1YcmMN2ITH0JAFdqKgYp0FpuNpvL7Bzb4fH9Wx5WHrlEpJshJOVpBLiPAZXR4f8qJaPkSYewuXGx6onAhJMnlUzkmscn8BLQG0BNASx0lLcFp27p+V2ApGtWhB4zUSICxKTdJPCIvQt50ZMBbFms3R6WTh043rHbAWR85aMDJ5RPJTBRPfCWkK6PRdYYaNYObU0mVijLKwbyYP2o4YS0ulhE4ul6VRmImlmW1vdSQrgDmxkdoyxT9rfJ3zbD8xh/FByQSQjeUyh7Gm7yCE8qZmdY0L39LbldujiJhcrqVYY7v5myJt/oTDKdIkQQzspECyyku1CpJyToeRgsRc8HOYmLw99vPcTXYRbR1MRx0oJE6SS+ZZM1MD2QuRFpCUZC7Ok7YTWxUQdynrJt0rR6qsVBylkw3xAkljfr63Jy4q0vQ6pmZc5OZ6Mf188v3k2v2K7+gzGzwNzbAuZElCh9IWOaAgvsBevVIZNZdrTYCJ4zCajkce51dLfmelMBN0xpdyl+dkQVrKnzkBowPso5foSqHlkmwnxugeV8qiT9UdJuvgj9YUGUqkukyO174zI4AnaiqV5jXlIM/ae7LrO82YfQKXh4Xz8SaA0ScCRt/vPpAoIgjgaBrsIyoNqdw0nItKeU7kvQRKAKUlxP0ElPIb3CPCpPSJ4ugZ5Kk3Ofl6S0P+9ClhU+pZAE0Bmu4FTRl+8swcZZzKHPHDqWAr5WyF18LJxVZevNh6aGQHoQWGsu+jVXwM5UEFlQ9tpZ89YI5KeXYz0rguqAPEhs86UqzYLMBOH4qdPqiA1tnzpUDgZ4Cfia7x4WeMcc+QJVnQ4ciwZJO5HE2s4vWbqNUfIHKe03uJn0DXlBAHdE0JuiZ+ZTxYXAfO1LH9J3We+LwDnM2x7cN/6faK5SzPnrcbrVUfp97ieoZp5G7s6CmAWACx3EBshLsAv5Zr8lc+8iZKua8dHSbj4G/sFNHUk4KqnKUBUi2NVKMYDSA1EQIgFUAqG6Su/OTZ85owm9WeZzwrKQeUCij1HlCqhEaCbtI3+AGqlmvyUUNVeDMDoGr5iX8YUJWs2LYf0hcXAa8mQgCvAl5l49VNZwHQCqD1AYBWRRMFk3QKIGu5Jh81ZH0JkBUga+mJfxiQdeZNbLpUAWBNhABgBcDKBqxpVwG4CnD1AcBV0qchQNVyTT5qqPoKoCpA1dIT/zCgKonzc4CpiRCAqQBT2TB16SYAUQGiPgCISpfZP7QeoNRyTT5qlJr7uf8imgKUWlwaoNSCKPX7iT2bTf4CeJoIAXgK8HTz04wr/3jAuJTx+fLM58q7Abk53eSeXy836P8U2TD3/Xz5L07+ZqwywP2CnG9Lk3jR4pYtmg1PXTIu7F/f8c4ux1okkvTL/CQ90NRwuR/hbrd45HOPMo+Q9Rip7FxknHPPHJ5n6ZhSPD4tL+cmBrw838vfvgUn3wkpNgFEd+GMVm69gSsOcOOxbI101Ec6UkVk5LgyE2fsraqRoAtDRGGrKBgXVk8wZOMAjRURZAqfGLJWGfx4iYlymf2JdI0xnrwdb2E5BjFnhcj6qMgqqlhgktOMTepM7dDmJUhWRevSoLn7KraIgS6MLixTG23GHAIsWuwEwUWEfEQ9yyBbfVTxYATRlC9l88rSVOWAxHOFRCkKsT0ysA9jpDNkVTBJLw5J7lHYncSxTmPelWVcDXvaASkCi0gk9i2okqWgy1Se1R3kYqFRIVEjMrKZlZd+S/bRWVmMVYa9rHRn9p23KLJ/XSVMtUhI0camcST72O1+V4pzkzSPJjETQZcSiZWhl5hEpbykJUsZIkZcBKE3l0iYT/EwOjEvXXoWs8px96yXltnpvDp987plvXp1+mznxW1tZs8K8m/mDqS2bbkbTL7g6WKGi9AzCRm9bdYErmUapeZrz3GI/QKCVq6+pwMN7Vve3vMV3y1vjmaknja2iTdvuDic4eln7DcCyn3NnB/Rg4+NuTfFs0acn5D06xb7/4wsPgYYy42BqdNstwk7WDDjYXx1O/RNJjSXNfltEVf6asVpI0PLmXabZExMbz7KgbYTY9/yiW1TANtYq8y33c/4kZlBtNSDIZQLEk8zODBWy8yitTwJkfCN4zrh8iik23SDwJucTbeKl6UJyHBWjW9fuauFCWyhSzjBIunHXhbOlHnl7LReo5da6yO/LqPa9nr7Dqkm2UJll1I65aebM78EFawG14NeDuIngxMWU4f6UGZs2Qtn7Xho7dTQsrW2O9/eNtt4vMJYkinJkx0xiRa6R2FKgi5Xf2/WQfPbmXeHN+qtyzbrxhCSWsy67rpss+4l0Y+3UXNZsllvZPuhu9nkqmg9U7n6qXSiOvFEdQ6aqE7ORIkiMgwL5uvA+WKeHydTtlfaP1rxRWoGmTelBxk/ELGRXXP7GYl4uciG3m5zV+v3MPa8vDL0jpeHK4GZzilHGTRXzRFog2ZOoXe8qlYbNCHLEWgjSQ9Cb3pdrUKSlCNHoJMk6p9Wq4/Og9TFju8b0xvfFNMJ+xPjOYqJP5z8YHUzyX5Wj972toxmVm3mK2X5LNSD1Uve51sipNsqo53trygdrYrYLwxHCmqXUdDmO/tHq57siyqRajplVLN+R+zI1MJ8QDLSRyEsm3oa+ZcqgnUIkejhns4nIh2moTBLblo9cZk83X2UsaqVupMeqUfHSvEous1VQbr5xXxOlsTldmr5Z6qGa8/xbuFRjdQd8YmWtJ6Ul8tTLml7olL1o57tdTzWbe5QWo5NZIpjwmhZbCSUGp5q13/hSSh6bmgTF6at/vaP/wMiEGYIYgMBAA=='
export const fullReportDefinitionResult = {
  layouts: [{ FIELD_STANDARD_LAYOUT: false, KEY_SCRIPT_ID: 'CUSTOMLAYOUT_4_T2257860_557' }],
  components: [
    {
      KEY_COMPONENT: 302,
      FLAG_SECONDARY_DIM: false,
      FIELD_CLASS: 'com.netledger.app.reporting.dimension.NLFinancialLayoutDimension',
    },
    {
      KEY_COMPONENT: 301,
      FLAG_SECONDARY_DIM: false,
      FIELD_CLASS: 'com.netledger.app.reporting.measure.NLFinancialMeasure',
    },
    {
      KEY_COMPONENT: 300,
      FLAG_SECONDARY_DIM: false,
      FIELD_CLASS: 'com.netledger.app.reporting.measure.NLFinancialBudgetMeasure',
    },
  ],
  parameters: { accounting_book_current_id: '1', range: 'all', accounting_book_id: '1' },
  sorts: [
    {
      KEY_COMPONENT: '302',
      FIELD_ALIAS: 'norderby1',
      FIELD_TABLE: 'finanbuckets',
      SEQ_NUMBER: -100,
      FLAG_DESCENDING: false,
      FLAG_SUBTOTAL: false,
    },
    {
      KEY_COMPONENT: '302',
      FIELD_ALIAS: 'norderby2',
      FIELD_TABLE: 'finanbuckets',
      SEQ_NUMBER: -99,
      FLAG_DESCENDING: false,
      FLAG_SUBTOTAL: false,
    },
  ],
  fields: [
    {
      KEY_COMPONENT: 302,
      FIELD_TABLE: 'FINANBUCKETS',
      FIELD_ALIAS: 'NKEY',
      FLAG_DIMENSION: false,
      FIELD_UNIT_TYPE: -1,
      FLAG_ROLLUP: false,
      FIELD_DATE_FILTER_INDEX: 0,
      FLAG_APPLY_FORWARDING: true,
      FLAG_MEASURE: false,
      SEQ_NUMBER: 0,
      FLAG_DUAL_COLUMN: false,
      FLAG_PERCENT_TOTAL: false,
      FLAG_PERCENT_INCOME: false,
      FLAG_PERCENT_EXPENSE: false,
      FLAG_RUNNING_BAL: false,
      FLAG_SHOW_OPENING_BAL: false,
      FLAG_SHOW_ABS_DIFF: false,
      FLAG_SHOW_PCT_DIFF: false,
      FLAG_SUB_TOTAL: false,
      FLAG_DISPLAY: false,
      FLAG_DROP_DECIMAL: false,
      FLAG_DIV_BY_THOUSAND: false,
      FLAG_NEG_IN_RED: false,
      FIELD_NEG_VAL_FORMAT: 'norm',
      FIELD_FORMAT: 'select',
      FLAG_TOTAL_FORMULA: true,
    },
    {
      KEY_COMPONENT: 302,
      FIELD_TABLE: 'FINANBUCKETS',
      FIELD_ALIAS: 'SRAWFULLKEY',
      FLAG_DIMENSION: false,
      FIELD_UNIT_TYPE: -1,
      FLAG_ROLLUP: false,
      FIELD_DATE_FILTER_INDEX: 0,
      FLAG_APPLY_FORWARDING: true,
      FLAG_MEASURE: false,
      SEQ_NUMBER: 0,
      FLAG_DUAL_COLUMN: false,
      FLAG_PERCENT_TOTAL: false,
      FLAG_PERCENT_INCOME: false,
      FLAG_PERCENT_EXPENSE: false,
      FLAG_RUNNING_BAL: false,
      FLAG_SHOW_OPENING_BAL: false,
      FLAG_SHOW_ABS_DIFF: false,
      FLAG_SHOW_PCT_DIFF: false,
      FLAG_SUB_TOTAL: false,
      FLAG_DISPLAY: false,
      FLAG_DROP_DECIMAL: false,
      FLAG_DIV_BY_THOUSAND: false,
      FLAG_NEG_IN_RED: false,
      FIELD_NEG_VAL_FORMAT: 'norm',
      FIELD_FORMAT: 'text',
      FLAG_TOTAL_FORMULA: true,
    },
    {
      KEY_COMPONENT: 302,
      FIELD_TABLE: 'FINANBUCKETS',
      FIELD_ALIAS: 'STYPE',
      FLAG_DIMENSION: false,
      FIELD_UNIT_TYPE: -1,
      FLAG_ROLLUP: false,
      FIELD_DATE_FILTER_INDEX: 0,
      FLAG_APPLY_FORWARDING: true,
      FLAG_MEASURE: false,
      SEQ_NUMBER: 0,
      FLAG_DUAL_COLUMN: false,
      FLAG_PERCENT_TOTAL: false,
      FLAG_PERCENT_INCOME: false,
      FLAG_PERCENT_EXPENSE: false,
      FLAG_RUNNING_BAL: false,
      FLAG_SHOW_OPENING_BAL: false,
      FLAG_SHOW_ABS_DIFF: false,
      FLAG_SHOW_PCT_DIFF: false,
      FLAG_SUB_TOTAL: false,
      FLAG_DISPLAY: false,
      FLAG_DROP_DECIMAL: false,
      FLAG_DIV_BY_THOUSAND: false,
      FLAG_NEG_IN_RED: false,
      FIELD_NEG_VAL_FORMAT: 'norm',
      FIELD_FORMAT: 'text',
      FLAG_TOTAL_FORMULA: true,
    },
    {
      KEY_COMPONENT: 302,
      FIELD_TABLE: 'FINANBUCKETS',
      FIELD_ALIAS: 'SRAWFULLNAME',
      FLAG_DIMENSION: false,
      FIELD_UNIT_TYPE: -1,
      FLAG_ROLLUP: true,
      FIELD_DATE_FILTER_INDEX: 0,
      FLAG_APPLY_FORWARDING: true,
      FLAG_MEASURE: false,
      SEQ_NUMBER: 1,
      FIELD_LABEL: 'Financial Row',
      FLAG_DUAL_COLUMN: false,
      FLAG_PERCENT_TOTAL: false,
      FLAG_PERCENT_INCOME: false,
      FLAG_PERCENT_EXPENSE: false,
      FLAG_RUNNING_BAL: false,
      FLAG_SHOW_OPENING_BAL: false,
      FLAG_SHOW_ABS_DIFF: false,
      FLAG_SHOW_PCT_DIFF: false,
      FLAG_SUB_TOTAL: false,
      FLAG_DISPLAY: true,
      FLAG_DROP_DECIMAL: false,
      FLAG_DIV_BY_THOUSAND: false,
      FLAG_NEG_IN_RED: false,
      FIELD_NEG_VAL_FORMAT: 'norm',
      FIELD_FORMAT: 'text',
      FLAG_TOTAL_FORMULA: true,
    },
    {
      KEY_COMPONENT: 302,
      FIELD_TABLE: 'FINANBUCKETS',
      FIELD_ALIAS: 'SRAWVALIDNAME',
      FLAG_DIMENSION: false,
      FIELD_UNIT_TYPE: -1,
      FLAG_ROLLUP: true,
      FIELD_DATE_FILTER_INDEX: 0,
      FLAG_APPLY_FORWARDING: true,
      FLAG_MEASURE: false,
      SEQ_NUMBER: 2,
      FIELD_LABEL: 'Financial Row',
      FIELD_URL:
        '/app/reporting/reportrunner.nl?cr=293&amp;regtx,tranline,kacct,x,x,CHILDRENOF,x,x={finandim,finanbuckets,svalidkey1,x,x}',
      FIELD_URL_TYPE: 'SIMPLE',
      FLAG_DUAL_COLUMN: false,
      FLAG_PERCENT_TOTAL: false,
      FLAG_PERCENT_INCOME: false,
      FLAG_PERCENT_EXPENSE: false,
      FLAG_RUNNING_BAL: false,
      FLAG_SHOW_OPENING_BAL: false,
      FLAG_SHOW_ABS_DIFF: false,
      FLAG_SHOW_PCT_DIFF: false,
      FLAG_SUB_TOTAL: false,
      FLAG_DISPLAY: true,
      FLAG_DROP_DECIMAL: false,
      FLAG_DIV_BY_THOUSAND: false,
      FLAG_NEG_IN_RED: false,
      FIELD_NEG_VAL_FORMAT: 'norm',
      FIELD_FORMAT: 'text',
      FLAG_TOTAL_FORMULA: true,
    },
    {
      KEY_COMPONENT: 301,
      FIELD_ALIAS: 'MSIAMT',
      FLAG_DIMENSION: false,
      FIELD_UNIT_TYPE: -1,
      FLAG_ROLLUP: false,
      FIELD_DATE_FILTER_INDEX: 1,
      FLAG_APPLY_FORWARDING: true,
      FIELD_ALT_DATE_SEGMENT: 'ACCOUNTING_PERIOD',
      FLAG_MEASURE: true,
      SEQ_NUMBER: 3,
      FIELD_LABEL: 'Amount',
      FIELD_URL: 'cr=-206',
      FIELD_URL_TYPE: 'FINANCIAL',
      FLAG_DUAL_COLUMN: false,
      FLAG_PERCENT_TOTAL: false,
      FLAG_PERCENT_INCOME: false,
      FLAG_PERCENT_EXPENSE: false,
      FLAG_RUNNING_BAL: false,
      FLAG_SHOW_OPENING_BAL: false,
      FLAG_SHOW_ABS_DIFF: false,
      FLAG_SHOW_PCT_DIFF: false,
      FLAG_SUB_TOTAL: true,
      FLAG_DISPLAY: true,
      FIELD_SUMMARY: ' COUNT',
      FLAG_DROP_DECIMAL: false,
      FLAG_DIV_BY_THOUSAND: false,
      FLAG_NEG_IN_RED: false,
      FIELD_NEG_VAL_FORMAT: 'trail',
      FIELD_FORMAT: 'currency',
      FLAG_TOTAL_FORMULA: true,
    },
  ],
  uiPreferences: {
    PARAMETER_CASH_BASIS: false,
    PARAMETER_TAXCASH_BASIS: 'F',
    PARAMETER_SHOW_ZEROS: true,
    PARAMETER_SHOW_SINGLEROWLINES: true,
    PARAMETER_DISPLAY_TYPE: 'data',
    PARAMETER_INC_VS_EXP: false,
    PARAMETER_GRAPH_TOP: 100001,
    PARAMETER_WEB_STORE: false,
    PARAMETER_ACTIVITY_ONLY: true,
    PARAMETER_ALLOW_WEBQUERY: false,
    PARAMETER_GRAPH_3D: false,
    PARAMETER_SHOW_CURRENCY_SYMBOL: true,
    PARAMETER_EXPAND_LEVEL: -1,
    PARAMETER_SECOND_DIMENSION: 'all',
  },
  criteria: [
    {
      descriptor: {
        FIELD_ALIAS: 'BNKEY',
        FIELD_OP_CLASS: 'IN',
        FILED_TYPE: 'SELECT',
        SEQ_NUMBER: -3,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: false,
        FLAG_VIRTUAL_FIELD: false,
        FIELD_DESCRIPTOR: 'fbudg,x,bnkey,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [{ FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: 1 }],
    },
    {
      descriptor: {
        FIELD_ALIAS: 'KPERIOD',
        FIELD_OP_CLASS: 'BEFOREEND',
        FILED_TYPE: 'PERIOD',
        SEQ_NUMBER: 0,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: false,
        FLAG_VIRTUAL_FIELD: true,
        FIELD_DESCRIPTOR: 'finan,trandoc,kperiod,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [
        { FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: 'TP' },
        { FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 1, FIELD_VALUE: 33 },
        { FIELD_DATE_FILTER_INDEX: 1, SEQ_NUMBER: 0, FIELD_VALUE: 'Q1LFY', FIELD_DATE_RANGE_TYPE: 'REL_REPORT' },
        { FIELD_DATE_FILTER_INDEX: 1, SEQ_NUMBER: 1, FIELD_VALUE: 2 },
      ],
    },
    {
      descriptor: {
        FIELD_ALIAS: 'KSUBSIDIARY',
        FIELD_OP_CLASS: 'SUBSIDCHILDRENOF',
        FILED_TYPE: 'SUBSIDIARY',
        SEQ_NUMBER: 1,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: false,
        FLAG_VIRTUAL_FIELD: true,
        FIELD_DESCRIPTOR: 'finan,tranline,ksubsidiary,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [{ FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: -1 }],
    },
    {
      descriptor: {
        FIELD_ALIAS: 'KCLASS',
        FIELD_OP_CLASS: 'IN',
        FILED_TYPE: 'CDL',
        SEQ_NUMBER: 2,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: true,
        FLAG_VIRTUAL_FIELD: true,
        FIELD_DESCRIPTOR: 'finan,tranline,kclass,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [{ FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: '- All -' }],
    },
    {
      descriptor: {
        FIELD_ALIAS: 'KDEPARTMENT',
        FIELD_OP_CLASS: 'IN',
        FILED_TYPE: 'CDL',
        SEQ_NUMBER: 3,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: true,
        FLAG_VIRTUAL_FIELD: true,
        FIELD_DESCRIPTOR: 'finan,tranline,kdepartment,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [{ FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: '- All -' }],
    },
    {
      descriptor: {
        FIELD_ALIAS: 'KLOCATION',
        FIELD_OP_CLASS: 'IN',
        FILED_TYPE: 'CDL',
        SEQ_NUMBER: 4,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: true,
        FLAG_VIRTUAL_FIELD: true,
        FIELD_DESCRIPTOR: 'finan,tranline,klocation,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [{ FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: '- All -' }],
    },
    {
      descriptor: {
        FIELD_ALIAS: 'KITEM',
        FIELD_OP_CLASS: 'IN',
        FILED_TYPE: 'CDL',
        SEQ_NUMBER: 5,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: true,
        FLAG_VIRTUAL_FIELD: true,
        FIELD_DESCRIPTOR: 'finan,tranline,kitem,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [{ FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: '- All -' }],
    },
    {
      descriptor: {
        FIELD_ALIAS: 'KCUSTJOB',
        FIELD_OP_CLASS: 'IN',
        FILED_TYPE: 'CDL',
        SEQ_NUMBER: 6,
        FIELD_UNIT_TYPE: -1,
        FLAG_IN_FOOTER: true,
        FLAG_CUSTOM_FOOTER: true,
        FLAG_VIRTUAL_FIELD: true,
        FIELD_DESCRIPTOR: 'finan,x,allcj,x,x',
        FLAG_IS_HIDDEN: false,
      },
      values: [{ FIELD_DATE_FILTER_INDEX: 0, SEQ_NUMBER: 0, FIELD_VALUE: '- All -' }],
    },
  ],
  flags: {
    KEY_REPORT_ID: 312,
    KEY_SCRIPT_ID: 'CUSTOMREPORT_312_T2257860_312',
    FIELD_KEY: 312,
    FIELD_CODE: 'FINANCIAL_BALANCE_SHEET_STMT',
    FIELD_DESCRIPTION: 'test fetch reportDefinition',
    FIELD_NAME: 'ShalomTest FinancialLayout',
    FIELD_ORIGINAL_TITLE: 'ShalomTest FinancialLayout',
    FIELD_PERM_TYPE: 'REPO_FINANCIALS',
    KEY_FEATURE: 'ACCOUNTING',
    FLAG_PERIODS_ALLOWED: true,
    FLAG_DISPLAY_TYPE: 'SUMMARY',
    FLAG_ONE_DATE: true,
    FLAG_PRIMARY_OUTER_JOIN: true,
    FLAG_CUSTOM_MODE: true,
    FLAG_CASH_BASIS: false,
    FLAG_SHOW_ZEROS: true,
    FLAG_INACTIVE: false,
    FIELD_VERSION: 2008,
    FLAG_PERIODS_ON: true,
    FLAG_USE_FISCAL_YEAR_RANGE: false,
    FLAG_USE_TAX_PERIODS: false,
    KEY_ENTITY: '7',
    FLAG_SHOW_LINK: true,
    FLAG_SUPPORTS_CONSOL_SUBSIDIARY: true,
    KEY_DEF_TOGGLE: -206,
    FIELD_TOGGLE_TYPE: 'DETAIL',
    FIELD_TOGGLE_URL: '/app/reporting/reportrunner.nl?cr=-206&amp;fromreport=312',
    FLAG_AFFECTED_BY_COGS: true,
    FLAG_ACTIVITY_ONLY: true,
  },
}
