/**
 * Forms Mock Instances
 */
const firstFormMock = {
  portalId: 6774238,
  guid: '3e2e7ef3-d0d4-418f-92e0-ad40ae2b622c',
  name: 'formTest1',
  action: '',
  method: 'POST',
  cssClass: 'abc',
  followUpId: 'DEPRECATED',
  editable: true,
  createdAt: 1571588456053,
  cloneable: true,
}

const secondFormMock = {
  portalId: 6774238,
  guid: '123e11f3-111-418f-92e0-cwwwe2b6999',
  name: 'formTest2',
  action: '',
  method: 'POST',
  cssClass: 'css',
  followUpId: 'DEPRECATED',
  editable: false,
  createdAt: 1561581451052,
  cloneable: true,
  captchaEnabled: false,
}

export const formsMockArray = [
  firstFormMock,
  secondFormMock,
] as unknown

export const beforeFormMock = {
  name: 'beforeUpdateInstance',
  guid: 'guid',
  cssClass: 'abc',
  followUpId: 'DEPRECATED',
  editable: true,
  cloneable: true,
  captchaEnabled: false,
  createdAt: 1500588456053,
  formFieldGroups: [
    {
      fields: [
        {
          name: 'g1',
          label: 'g1',
          type: 'string',
          fieldType: 'text',
          description: '',
          required: false,
          hidden: false,
          defaultValue: '',
          isSmartField: false,
          selectedOptions: [],
          options: [],
        },
      ],
      default: true,
      isSmartGroup: false,
    },
  ],
}

export const afterFormMock = {
  name: 'afterUpdateInstance',
  guid: 'guid',
  followUpId: 'DEPRECATED',
  editable: true,
  cloneable: true,
  captchaEnabled: false,
  redirect: 'google.com',
  createdAt: 9999999999999,
  formFieldGroups: [
    {
      fields: [
        {
          name: 'g1',
          label: 'g1',
          type: 'string',
          fieldType: 'text',
          description: '',
          required: false,
          hidden: false,
          defaultValue: '',
          isSmartField: false,
          selectedOptions: [],
          options: [],
        },
      ],
      default: true,
      isSmartGroup: false,
    },
    {
      fields: [
        {
          name: 'state',
          label: 'State/Region',
          type: 'string',
          fieldType: 'text',
          description: '',
          required: false,
          hidden: false,
          defaultValue: '',
          isSmartField: false,
          selectedOptions: [],
          options: [
            {
              label: 'opt1',
              value: 'val1',
              hidden: true,
              readOnly: true,
            },
          ],
        },
      ],
      default: true,
      isSmartGroup: false,
    },
  ],
}

/**
 * Workflow Mock Instances
 */
const firstWorkflowMock = {
  id: 12345,
  name: 'workflowTest1',
  type: 'PROPERTY_ANCHOR"',
  unsupportedField: 'bla',
  enabled: true,
  insertedAt: 13423432,
  updatedAt: 2423432,
  internal: false,
  onlyExecOnBizDays: false,
  listening: true,
  allowContactToTriggerMultipleTimes: true,
  onlyEnrollManually: false,
  enrollOnCriteriaUpdate: true,
  lastUpdatedBy: 'asb@gm.il',
  supressionListIds: [
    1234,
    1,
  ],
  eventAnchor: {
    contactPropertyAnchor: 'hs_content_membership_registered_at',
  },
  nurtureTimeRange: {
    enabled: false,
    startHour: 9,
    stopHour: 10,
  },
  actions: [
    {
      type: 'DELAY',
      delayMillis: 0,
      actionId: 170629910,
      anchorSetting: {
        execTimeOfDay: '11:30 AM',
        execTimeInMinutes: 690,
        boundary: 'ON',
      },
      stepId: 2,
    },
    {
      type: 'SET_CONTACT_PROPERTY',
      propertyName: 'fax',
      newValue: 'abcdefg',
      actionId: 170629911,
      stepId: 2,
    },
    {
      type: 'BRANCH',
      actionId: 170629912,
      filtersListId: 29,
      stepId: 2,
      acceptActions: [
        {
          type: 'SMS_NOTIFICATION',
          staticTo: '+113455333434',
          body: 'Hello world',
          actionId: 170629913,
          stepId: 1,
        },
      ],
      rejectActions: [
        {
          type: 'SMS_NOTIFICATION',
          staticTo: '+113455333434',
          body: 'Hello world',
          actionId: 170629913,
          stepId: 1,
        },
      ],
    },
  ],
}

const secondWorkflowMock = {
  id: 123456,
  name: 'workflowTest2',
  type: 'PROPERTY_ANCHOR"',
  unsupportedField: 'bla',
  enabled: true,
  insertedAt: 13423432,
  updatedAt: 2423432,
  internal: false,
  onlyExecOnBizDays: false,
  listening: true,
  allowContactToTriggerMultipleTimes: true,
  onlyEnrollManually: false,
  enrollOnCriteriaUpdate: true,
  lastUpdatedBy: 'asb@gm.il',
  supressionListIds: [
    1234,
    1,
  ],
  eventAnchor: {
    contactPropertyAnchor: 'hs_content_membership_registered_at',
  },
  nurtureTimeRange: {
    enabled: false,
    startHour: 9,
    stopHour: 10,
  },
  actions: [
    {
      type: 'DELAY',
      delayMillis: 0,
      actionId: 170629910,
      anchorSetting: {
        execTimeOfDay: '11:30 AM',
        execTimeInMinutes: 690,
        boundary: 'ON',
      },
      stepId: 2,
    },
    {
      type: 'SET_CONTACT_PROPERTY',
      propertyName: 'fax',
      newValue: 'abcdefg',
      actionId: 170629911,
      stepId: 2,
    },
    {
      type: 'BRANCH',
      actionId: 170629912,
      filtersListId: 29,
      stepId: 2,
      acceptActions: [
        {
          type: 'SMS_NOTIFICATION',
          staticTo: '+113455333434',
          body: 'Hello world',
          actionId: 170629913,
          stepId: 1,
        },
      ],
      rejectActions: [
        {
          type: 'SMS_NOTIFICATION',
          staticTo: '+113455333434',
          body: 'Hello world',
          actionId: 170629913,
          stepId: 1,
        },
      ],
    },
  ],
}

export const workflowsMock = {
  id: 1234,
  name: 'workflowTest',
  type: 'PROPERTY_ANCHOR"',
  unsupportedField: 'bla',
  enabled: true,
  insertedAt: 13423432,
  updatedAt: 2423432,
  internal: false,
  onlyExecOnBizDays: false,
  listening: true,
  allowContactToTriggerMultipleTimes: true,
  onlyEnrollManually: false,
  enrollOnCriteriaUpdate: true,
  lastUpdatedBy: 'asb@gm.il',
  supressionListIds: [
    1234,
    1,
  ],
  eventAnchor: {
    contactPropertyAnchor: 'hs_content_membership_registered_at',
  },
  nurtureTimeRange: {
    enabled: false,
    startHour: 9,
    stopHour: 10,
  },
  actions: [
    {
      type: 'DELAY',
      delayMillis: 0,
      actionId: 170629910,
      anchorSetting: {
        execTimeOfDay: '11:30 AM',
        execTimeInMinutes: 690,
        boundary: 'ON',
      },
      stepId: 2,
    },
    {
      type: 'SET_CONTACT_PROPERTY',
      propertyName: 'fax',
      newValue: 'abcdefg',
      actionId: 170629911,
      stepId: 2,
    },
    {
      type: 'BRANCH',
      actionId: 170629912,
      filtersListId: 29,
      stepId: 2,
      acceptActions: [
        {
          type: 'SMS_NOTIFICATION',
          staticTo: '+113455333434',
          body: 'Hello world',
          actionId: 170629913,
          stepId: 1,
        },
      ],
      rejectActions: [
        {
          type: 'SMS_NOTIFICATION',
          staticTo: '+113455333434',
          body: 'Hello world',
          actionId: 170629913,
          stepId: 1,
        },
      ],
    },
  ],
}

export const workflowsCreateResponse = {
  portalId: 62515,
  id: 9274658,
  name: workflowsMock.name,
  updatedAt: 1579426531143,
  insertedAt: 1579426531213,
  type: workflowsMock.type,
  enabled: workflowsMock.enabled,
  description: '',
  contactCounts: {
    active: 0,
    enrolled: 0,
  },
  eventAnchor: {
    contactPropertyAnchor: 'hs_content_membership_registered_at',
  },
  migrationStatus: {
    portalId: 62515,
    flowId: 7102706,
    workflowId: 5488642,
    migrationStatus: 'EXECUTION_MIGRATED',
    platformOwnsActions: true,
    lastSuccessfulMigrationTimestamp: null,
  },
  originalAuthorUserId: 215482,
  creationSource: {
    sourceApplication: {
      source: 'WORKFLOWS_APP',
      serviceName: 'https://app.hubspot.com/workflows/6962502/platform/create/new',
    },
    createdByUser: {
      userId: 9379192,
      userEmail: 'adam.rosenthal@salto.io',
    },
    createdAt: 1579069732474,
  },
  updateSource: {
    sourceApplication: {
      source: 'WORKFLOWS_APP',
      serviceName: 'https://app.hubspot.com/workflows/6962502/platform/flow/18538464/edit/actions/enrollment/filters',
    },
    updatedByUser: {
      userId: 9379192,
      userEmail: 'adam.rosenthal@salto.io',
    },
    updatedAt: 1579070462059,
    contactListIds: {
      enrolled: 20,
      active: 21,
      completed: 22,
      succeeded: 23,
    },
  },
  internal: false,
  onlyExecOnBizDays: false,
  listening: true,
  allowContactToTriggerMultipleTimes: true,
  onlyEnrollManually: false,
  enrollOnCriteriaUpdate: true,
  lastUpdatedBy: 'asb@gm.il',
  supressionListIds: [
    12345,
    12,
  ],
  nurtureTimeRange: {
    enabled: false,
    startHour: 9,
    stopHour: 10,
  },
  actions: [
    {
      type: 'DELAY',
      delayMillis: 0,
      actionId: 170629910,
      anchorSetting: {
        execTimeOfDay: '11:30 AM',
        execTimeInMinutes: 690,
        boundary: 'ON',
      },
      stepId: 2,
    },
    {
      type: 'SET_CONTACT_PROPERTY',
      propertyName: 'fax',
      newValue: 'abcdefg',
      actionId: 170629911,
      stepId: 2,
    },
    {
      type: 'BRANCH',
      actionId: 170629912,
      filtersListId: 29,
      stepId: 2,
      acceptActions: [
        {
          type: 'SMS_NOTIFICATION',
          staticTo: '+113455333434',
          body: 'Hello world',
          actionId: 170629913,
          stepId: 1,
        },
      ],
      rejectActions: [
        {
          type: 'SMS_NOTIFICATION',
          staticTo: '+113455333434',
          body: 'Hello world',
          actionId: 170629913,
          stepId: 1,
        },
      ],
    },
  ],
}

export const workflowsMockArray = [
  firstWorkflowMock,
  secondWorkflowMock,
  workflowsMock,
]


/**
 * MarketingEmail Mock Instances
 */
const firstMarketingEmailMock = {
  ab: true,
  abHoursToWait: 12,
  abVariation: false,
  abSampleSizeDefault: 'MASTER',
  abSamplingDefault: 'MASTER',
  abStatus: 'MASTER',
  abSuccessMetric: 'OPENS_BY_DELIVERED',
  abTestId: '1234',
  abTestPercentage: 40,
  absoluteUrl: 'google.com',
  allEmailCampaignIds: [
    123,
  ],
  analyticsPageId: '1234',
  archived: false,
  author: 'mail@gmail.com',
  authorEmail: 'mail123@gmail.com',
  authorName: 'userName',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  clonedFrom: 1234,
  createPage: false,
  created: 12334567,
  currentlyPublished: true,
  domain: 'ynet.com',
  emailBody: 'main email body',
  emailNote: 'email notes',
  emailType: 'AB_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 1234,
  folderId: 999,
  freezeDate: 170456443,
  fromName: 'sender name',
  htmlTitle: 'title',
  id: 111111,
  isGraymailSuppressionEnabled: false,
  isLocalTimezoneSend: false,
  isPublished: true,
  name: 'marketingEmail instance name',
  authorAt: 124543,
  authorUserId: 12345,
  canSpamSettingsId: 67899,
  flexArea: {
    main: {
      boxFirstElementIndex: 0,
      boxLastElementIndex: 0,
      boxed: false,
      isSingleColumnFullWidth: false,
      sections: [
        {
          columns: [
            {
              id: 'builtin_column_0-0',
              widgets: ['builtin_module_0_0_0'],
              width: 12,
            },
          ],
          id: 'builtin_section-0',
          style: {
            backgroundColor: '#EAF0F6',
            backgroundType: 'CONTENT',
            paddingBottom: '10px',
            paddingTop: '10px',
          },
        },
      ],
    },
  },
  isRecipientFatigueSuppressionEnabled: false,
  leadFlowId: 1234,
  liveDomain: 'my-website.hs-sites.com',
  mailingListsExcluded: [1],
  mailingListsIncluded: [2],
  maxRssEntries: 5,
  metaDescription: '',
  pageExpirtyDate: 1234563463,
  pageExpiryRedirectId: 356,
  previewKey: 'abcDeGHY',
  processingStatus: 'UNDEFINED',
  publishDate: 12423432523,
  publishedAt: 143243253253,
  publishedById: 23,
  publishedByName: 'John Doe',
  publishImmediately: true,
  publishedUrl: '',
  replyTo: 'mail@gmail.com',
  resolvedDomain: 'ynet.com',
  rssEmailAuthorLineTemplate: 'By, ',
  rssEmailNlogImageMaxWidth: 300,
  rssEmailByTest: 'By',
  rssEmailClickThroughText: 'Read more',
  rssEmailCommentText: 'Comment',
  rssEmailEntryTemplate: '',
  rssEmailEntryTemplateEnabled: false,
  rssEmailUrl: '',
  rssToEmailTiming: {
    repeats: 'daily',
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_monthly: 1,
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_weekly: 1,
    time: '9:00 am',
  },
  slug: 'slug-23412423423',
  smartEmailFields: {},
  styleSettings: {
    // eslint-disable-next-line @typescript-eslint/camelcase
    background_color: '#EAF0F6',
  },
  subcategory: 'blog_email',
  subject: 'Subject line',
  subscription: 123456,
  subscriptionBlogId: 1234567890,
  // eslint-disable-next-line @typescript-eslint/camelcase
  subscription_name: 'Default HubSpot Blog Subscription',
  templatePath: 'generated_layouts/1345.html',
  trasactional: false,
  unpublishedAt: 0,
  updated: 1230005253,
  updatedById: 2,
  url: 'website-url.com',
  useRssHeadlineAsSubject: false,
  vidsExcluded: [1234],
  vidsIncluded: [12],
  widgets: {
    // eslint-disable-next-line @typescript-eslint/camelcase
    builtin_module_0_0_0: {
      body: {
        alignment: 'center',
        // eslint-disable-next-line @typescript-eslint/camelcase
        hs_enable_module_padding: true,
        img: {
          alt: 'HubSpot logo orange',
          height: 72,
          src: 'https://static.hsappstatic.net/TemplateAssets/static-1.46/img/hs_default_template_images/email_dnd_template_images/company-logo-orange.png',
          width: 240,
        },
        // eslint-disable-next-line @typescript-eslint/camelcase
        module_id: 1367093,
      },
      // eslint-disable-next-line @typescript-eslint/camelcase
      child_css: {},
      css: {},
      id: 'builtin_module_0_0_0',
      // eslint-disable-next-line @typescript-eslint/camelcase
      module_id: 1367093,
      name: 'builtin_module_0_0_0',
      order: 1,
      type: 'module',
    },
  },
  workflowNames: [],
}

const secondMarketingEmailMock = {
  ab: false,
  abHoursToWait: 4,
  abVariation: false,
  abSampleSizeDefault: 'MASTER',
  abSamplingDefault: 'MASTER',
  abStatus: 'VARIANT',
  abSuccessMetric: 'OPENS_BY_DELIVERED',
  abTestId: '1234',
  abTestPercentage: 30,
  absoluteUrl: 'google.com',
  allEmailCampaignIds: [],
  analyticsPageId: '432423',
  archived: false,
  author: 'mail1@gmail.com',
  authorEmail: 'mail13@gmail.com',
  authorName: 'userNameOther',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  clonedFrom: 1234,
  createPage: true,
  created: 12334567,
  currentlyPublished: true,
  domain: 'one.com',
  emailBody: 'main body',
  emailNote: 'emails notes',
  emailType: 'ABC_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 1234,
  folderId: 919,
  freezeDate: 170456443,
  fromName: 'sender name',
  htmlTitle: 'title',
  id: 222222,
  isGraymailSuppressionEnabled: true,
  isLocalTimezoneSend: true,
  isPublished: true,
  name: 'marketingEmail instance2 name',
  authorAt: 124543,
  authorUserId: 12345,
  canSpamSettingsId: 67899,
  flexArea: {
    main: {
      boxFirstElementIndex: 0,
      boxLastElementIndex: 0,
      boxed: false,
      isSingleColumnFullWidth: false,
      sections: [
        {
          columns: [
            {
              id: 'builtin_column_0-0',
              widgets: ['builtin_module_0_0_0'],
              width: 12,
            },
          ],
          id: 'builtin_section-0',
          style: {
            backgroundColor: '#EAF0F6',
            backgroundType: 'CONTENT',
            paddingBottom: '10px',
            paddingTop: '10px',
          },
        },
      ],
    },
  },
  isRecipientFatigueSuppressionEnabled: false,
  leadFlowId: 1234,
  liveDomain: 'my-website.hs-sites.com',
  mailingListsExcluded: [1],
  mailingListsIncluded: [2],
  maxRssEntries: 5,
  metaDescription: '',
  pageExpirtyDate: 1234563463,
  pageExpiryRedirectId: 356,
  previewKey: 'abcDeGHY',
  processingStatus: 'UNDEFINED',
  publishDate: 12423432523,
  publishedAt: 143243253253,
  publishedById: 23,
  publishedByName: 'John Doe',
  publishImmediately: true,
  publishedUrl: '',
  replyTo: 'mail@gmail.com',
  resolvedDomain: 'ynet.com',
  rssEmailAuthorLineTemplate: 'By, ',
  rssEmailNlogImageMaxWidth: 300,
  rssEmailByTest: 'By',
  rssEmailClickThroughText: 'Read more',
  rssEmailCommentText: 'Comment',
  rssEmailEntryTemplate: '',
  rssEmailEntryTemplateEnabled: false,
  rssEmailUrl: '',
  rssToEmailTiming: {
    repeats: 'daily',
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_monthly: 1,
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_weekly: 1,
    time: '9:00 am',
  },
  slug: 'slug-23412423423',
  smartEmailFields: {},
  styleSettings: {
    // eslint-disable-next-line @typescript-eslint/camelcase
    background_color: '#EAF0F6',
  },
  subcategory: 'blog_email',
  subject: 'Subject line 2',
  subscription: 123456,
  subscriptionBlogId: 1234567890,
  // eslint-disable-next-line @typescript-eslint/camelcase
  subscription_name: 'Default HubSpot Blog Subscription',
  templatePath: 'generated_layouts/1345.html',
  trasactional: false,
  unpublishedAt: 0,
  updated: 1230005253,
  updatedById: 2,
  url: 'website-url.com',
  useRssHeadlineAsSubject: false,
  vidsExcluded: [1234],
  vidsIncluded: [12],
  widgets: {
    // eslint-disable-next-line @typescript-eslint/camelcase
    builtin_module_0_0_0: {
      body: {
        alignment: 'center',
        // eslint-disable-next-line @typescript-eslint/camelcase
        hs_enable_module_padding: true,
        img: {
          alt: 'HubSpot logo orange',
          height: 72,
          src: 'https://static.hsappstatic.net/TemplateAssets/static-1.46/img/hs_default_template_images/email_dnd_template_images/company-logo-orange.png',
          width: 240,
        },
        // eslint-disable-next-line @typescript-eslint/camelcase
        module_id: 1367093,
      },
      // eslint-disable-next-line @typescript-eslint/camelcase
      child_css: {},
      css: {},
      id: 'builtin_module_0_0_0',
      // eslint-disable-next-line @typescript-eslint/camelcase
      module_id: 1367093,
      name: 'builtin_module_0_0_0',
      order: 1,
      type: 'module',
    },
  },
  workflowNames: [],
}

const thirdMarketingEmailMock = {
  ab: false,
  abHoursToWait: 11,
  abVariation: false,
  abSampleSizeDefault: 'VARIANT',
  abSamplingDefault: 'MASTER',
  abStatus: 'VARIANT',
  abSuccessMetric: 'OPENS_BY_DELIVERED',
  abTestId: '6543',
  abTestPercentage: 12345,
  absoluteUrl: 'google.com',
  allEmailCampaignIds: [],
  analyticsPageId: 'email ID',
  archived: false,
  author: 'mail,e@gmail.com',
  authorEmail: 'mail134@gmail.com',
  authorName: 'userNameOther1',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  clonedFrom: 1234,
  createPage: true,
  created: 12334567,
  currentlyPublished: true,
  domain: 'one.com',
  emailBody: 'main body',
  emailNote: 'emails notes',
  emailType: 'ABC_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 111,
  folderId: 919,
  freezeDate: 170456443,
  fromName: 'sender name',
  htmlTitle: 'title',
  id: 973287,
  isGraymailSuppressionEnabled: true,
  isLocalTimezoneSend: true,
  isPublished: true,
  name: 'marketingEmail instance3 name',
  authorAt: 124543,
  authorUserId: 12345,
  canSpamSettingsId: 67899,
  flexArea: {
    main: {
      boxFirstElementIndex: 0,
      boxLastElementIndex: 0,
      boxed: false,
      isSingleColumnFullWidth: false,
      sections: [
        {
          columns: [
            {
              id: 'builtin_column_0-0',
              widgets: ['builtin_module_0_0_0'],
              width: 12,
            },
          ],
          id: 'builtin_section-0',
          style: {
            backgroundColor: '#EAF0F6',
            backgroundType: 'CONTENT',
            paddingBottom: '10px',
            paddingTop: '10px',
          },
        },
      ],
    },
  },
  isRecipientFatigueSuppressionEnabled: false,
  leadFlowId: 1234,
  liveDomain: 'my-website.hs-sites.com',
  mailingListsExcluded: [1],
  mailingListsIncluded: [2],
  maxRssEntries: 5,
  metaDescription: '',
  pageExpirtyDate: 1234563463,
  pageExpiryRedirectId: 356,
  previewKey: 'abcDeGHY',
  processingStatus: 'UNDEFINED',
  publishDate: 12423432523,
  publishedAt: 143243253253,
  publishedById: 23,
  publishedByName: 'John Doe',
  publishImmediately: true,
  publishedUrl: '',
  replyTo: 'mail@gmail.com',
  resolvedDomain: 'ynet.com',
  rssEmailAuthorLineTemplate: 'By, ',
  rssEmailNlogImageMaxWidth: 300,
  rssEmailByTest: 'By',
  rssEmailClickThroughText: 'Read more',
  rssEmailCommentText: 'Comment',
  rssEmailEntryTemplate: '',
  rssEmailEntryTemplateEnabled: false,
  rssEmailUrl: '',
  rssToEmailTiming: {
    repeats: 'daily',
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_monthly: 1,
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_weekly: 1,
    time: '9:00 am',
  },
  slug: 'slug-23412423423',
  smartEmailFields: {},
  styleSettings: {
    // eslint-disable-next-line @typescript-eslint/camelcase
    background_color: '#EAF0F6',
  },
  subcategory: 'blog_email',
  subject: 'Subject line 2',
  subscription: 123456,
  subscriptionBlogId: 1234567890,
  // eslint-disable-next-line @typescript-eslint/camelcase
  subscription_name: 'Default HubSpot Blog Subscription',
  templatePath: 'generated_layouts/1345.html',
  trasactional: false,
  unpublishedAt: 0,
  updated: 1230005253,
  updatedById: 2,
  url: 'website-url.com',
  useRssHeadlineAsSubject: false,
  vidsExcluded: [1234],
  vidsIncluded: [12],
  widgets: {
    // eslint-disable-next-line @typescript-eslint/camelcase
    builtin_module_0_0_0: {
      body: {
        alignment: 'center',
        // eslint-disable-next-line @typescript-eslint/camelcase
        hs_enable_module_padding: true,
        img: {
          alt: 'HubSpot logo orange',
          height: 72,
          src: 'https://static.hsappstatic.net/TemplateAssets/static-1.46/img/hs_default_template_images/email_dnd_template_images/company-logo-orange.png',
          width: 240,
        },
        // eslint-disable-next-line @typescript-eslint/camelcase
        module_id: 1367093,
      },
      // eslint-disable-next-line @typescript-eslint/camelcase
      child_css: {},
      css: {},
      id: 'builtin_module_0_0_0',
      // eslint-disable-next-line @typescript-eslint/camelcase
      module_id: 1367093,
      name: 'builtin_module_0_0_0',
      order: 1,
      type: 'module',
    },
  },
  workflowNames: [],
}

export const marketingEmailMock = {
  name: 'newTestMarketingEmail',
  ab: false,
  abHoursToWait: 123,
  abVariation: false,
  abStatus: 'VARIANT',
  archived: false,
  author: 'mail,e@gmail.com',
  authorEmail: 'mail134@gmail.com',
  authorName: 'userNameOther1',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  clonedFrom: 1234,
  created: 12334567,
  emailBody: 'main body',
  emailType: 'ABC_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 111,
  folderId: 919,
  freezeDate: 170456443,
  fromName: 'sender name',
  id: 973111,
  isGraymailSuppressionEnabled: true,
  isLocalTimezoneSend: true,
  authorAt: 124543,
  authorUserId: 12345,
  canSpamSettingsId: 67899,
  categoryId: 2,
  contentCategoryType: 2,
  flexArea: '{"main":{"boxFirstElementIndex":0,"boxLastElementIndex":0,"boxed":false,"isSingleColumnFullWidth":false,"sections":[{"columns":[{"id":"builtin_column_0-0","widgets":["builtin_module_0_0_0"],"width":12}],"id":"builtin_section-0","style":{"backgroundColor":"#EAF0F6","backgroundType":"CONTENT","paddingBottom":"10px","paddingTop":"10px"}}]}}',
  isRecipientFatigueSuppressionEnabled: false,
  leadFlowId: 1234,
  liveDomain: 'my-website.hs-sites.com',
  mailingListsExcluded: [1],
  mailingListsIncluded: [2],
  maxRssEntries: 5,
  metaDescription: '',
  pageExpirtyDate: 1234563463,
  pageExpiryRedirectId: 356,
  previewKey: 'abcDeGHY',
  processingStatus: 'UNDEFINED',
  publishDate: 12423432523,
  publishedAt: 143243253253,
  publishedById: 23,
  publishedByName: 'John Doe',
  publishImmediately: true,
  publishedUrl: '',
  replyTo: 'mail@gmail.com',
  resolvedDomain: 'ynet.com',
  rssEmailAuthorLineTemplate: 'By, ',
  rssEmailNlogImageMaxWidth: 300,
  rssEmailByTest: 'By',
  rssEmailClickThroughText: 'Read more',
  rssEmailCommentText: 'Comment',
  rssEmailEntryTemplate: '',
  rssEmailEntryTemplateEnabled: false,
  rssEmailUrl: '',
  rssToEmailTiming: {
    repeats: 'daily',
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_monthly: 1,
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_weekly: 1,
    time: '9:00 am',
  },
  slug: 'slug-23412423423',
  smartEmailFields: '{}',
  styleSettings: '{ "background_color": "#EAF0F6" }',
  subcategory: 'blog_email',
  subject: 'Subject line 2',
  subscription: 123456,
  subscriptionBlogId: 1234567890,
  // eslint-disable-next-line @typescript-eslint/camelcase
  subscription_name: 'Default HubSpot Blog Subscription',
  templatePath: 'generated_layouts/1345.html',
  trasactional: false,
  unpublishedAt: 0,
  updated: 1230005253,
  updatedById: 2,
  url: 'website-url.com',
  useRssHeadlineAsSubject: false,
  vidsExcluded: [1234],
  vidsIncluded: [12],
  widgets: '{"builtin_module_0_0_0":{"body":{"alignment":"center","hs_enable_module_padding":true,"img":{"alt":"HubSpot logo orange","height":72,"src":"https://static.hsappstatic.net/TemplateAssets/static-1.46/img/hs_default_template_images/email_dnd_template_images/company-logo-orange.png","width":240},"module_id":1367093},"child_css":{},"css":{},"id":"builtin_module_0_0_0","module_id":1367093,"name":"builtin_module_0_0_0","order":1,"type":"module"}}',
  workflowNames: [],
}

export const marketingEmailCreateResponse = {
  name: 'newTestMarketingEmail',
  ab: false,
  abHoursToWait: 123,
  abVariation: false,
  abSampleSizeDefault: null,
  abSamplingDefault: null,
  abStatus: 'VARIANT',
  archived: false,
  author: 'mail,e@gmail.com',
  authorEmail: 'mail134@gmail.com',
  authorName: 'userNameOther1',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  clonedFrom: 1234,
  createPage: false,
  created: 12334567,
  currentlyPublished: false,
  domain: '',
  emailBody: 'main body',
  emailNote: '',
  emailType: 'ABC_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 111,
  folderId: 919,
  freezeDate: 170456443,
  fromName: 'sender name',
  htmlTitle: '',
  id: 1234566,
  isGraymailSuppressionEnabled: true,
  isLocalTimezoneSend: true,
  isPublished: false,
  authorAt: 124543,
  authorUserId: 12345,
  canSpamSettingsId: 67899,
  categoryId: 2,
  contentCategoryType: 2,
  flexArea: {
    main: {
      boxFirstElementIndex: 0,
      boxLastElementIndex: 0,
      boxed: false,
      isSingleColumnFullWidth: false,
      sections: [
        {
          columns: [
            {
              id: 'builtin_column_0-0',
              widgets: ['builtin_module_0_0_0'],
              width: 12,
            },
          ],
          id: 'builtin_section-0',
          style: {
            backgroundColor: '#EAF0F6',
            backgroundType: 'CONTENT',
            paddingBottom: '10px',
            paddingTop: '10px',
          },
        },
      ],
    },
  },
  isRecipientFatigueSuppressionEnabled: false,
  leadFlowId: 1234,
  liveDomain: 'my-website.hs-sites.com',
  mailingListsExcluded: [1],
  mailingListsIncluded: [2],
  maxRssEntries: 5,
  metaDescription: '',
  pageExpirtyDate: 1234563463,
  pageExpiryRedirectId: 356,
  previewKey: 'abcDeGHY',
  processingStatus: 'UNDEFINED',
  publishDate: 12423432523,
  publishedAt: 143243253253,
  publishedById: 23,
  publishedByName: 'John Doe',
  publishImmediately: true,
  publishedUrl: '',
  replyTo: 'mail@gmail.com',
  resolvedDomain: 'ynet.com',
  rssEmailAuthorLineTemplate: 'By, ',
  rssEmailNlogImageMaxWidth: 300,
  rssEmailByTest: 'By',
  rssEmailClickThroughText: 'Read more',
  rssEmailCommentText: 'Comment',
  rssEmailEntryTemplate: '',
  rssEmailEntryTemplateEnabled: false,
  rssEmailUrl: '',
  rssToEmailTiming: {
    repeats: 'daily',
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_monthly: 1,
    // eslint-disable-next-line @typescript-eslint/camelcase
    repeats_on_weekly: 1,
    time: '9:00 am',
  },
  slug: 'slug-23412423423',
  smartEmailFields: {},
  styleSettings: {
    // eslint-disable-next-line @typescript-eslint/camelcase
    background_color: '#EAF0F6',
  },
  subcategory: 'blog_email',
  subject: 'Subject line 2',
  subscription: 123456,
  subscriptionBlogId: 1234567890,
  // eslint-disable-next-line @typescript-eslint/camelcase
  subscription_name: 'Default HubSpot Blog Subscription',
  templatePath: 'generated_layouts/1345.html',
  trasactional: false,
  unpublishedAt: 0,
  updated: 1230005253,
  updatedById: 2,
  url: 'website-url.com',
  useRssHeadlineAsSubject: false,
  vidsExcluded: [1234],
  vidsIncluded: [12],
  widgets: {
    // eslint-disable-next-line @typescript-eslint/camelcase
    builtin_module_0_0_0: {
      body: {
        alignment: 'center',
        // eslint-disable-next-line @typescript-eslint/camelcase
        hs_enable_module_padding: true,
        img: {
          alt: 'HubSpot logo orange',
          height: 72,
          src: 'https://static.hsappstatic.net/TemplateAssets/static-1.46/img/hs_default_template_images/email_dnd_template_images/company-logo-orange.png',
          width: 240,
        },
        // eslint-disable-next-line @typescript-eslint/camelcase
        module_id: 1367093,
      },
      // eslint-disable-next-line @typescript-eslint/camelcase
      child_css: {},
      css: {},
      id: 'builtin_module_0_0_0',
      // eslint-disable-next-line @typescript-eslint/camelcase
      module_id: 1367093,
      name: 'builtin_module_0_0_0',
      order: 1,
      type: 'module',
    },
  },
  workflowNames: [],
}

export const marketingEmailMockArray = [
  firstMarketingEmailMock,
  secondMarketingEmailMock,
  thirdMarketingEmailMock,
  marketingEmailMock,
]
