/**
 * Forms Mock Instances
 */
const firstFormMock = {
  portalId: 6774238,
  guid: '3e2e7ef3-d0d4-418f-92e0-ad40ae2b622c',
  name: 'formTest1',
  action: '',
  method: 'POST',
  cssClass: 'abc',
  followUpId: 'DEPRECATED',
  editable: true,
  createdAt: 1571588456053,
  cloneable: true,
}

const secondFormMock = {
  portalId: 6774238,
  guid: '123e11f3-111-418f-92e0-cwwwe2b6999',
  name: 'formTest2',
  action: '',
  method: 'POST',
  cssClass: 'css',
  followUpId: 'DEPRECATED',
  editable: false,
  createdAt: 1561581451052,
  cloneable: true,
  captchaEnabled: false,
}

export const formsMockArray = [
  firstFormMock,
  secondFormMock,
] as unknown


/**
 * Workflow Mock Instances
 */
const firstWorkflowMock = {
  id: 12345,
  name: 'workflowTest1',
  type: 'DRIP_DELAY',
  unsupportedField: 'bla',
}

const secondWorkflowMock = {
  id: 54321,
  name: 'workflowTest1',
  type: 'DRIP_DELAY',
  enabled: false,
  contactListIds: {
    enrolled: 1,
    active: 2,
    completed: 3,
    succeeded: 4,

  },
}

export const workflowsMock = {
  id: 12345,
  name: 'Test Workflow',
  type: 'DRIP_DELAY',
  enabled: false,
  contactListIds: {
    enrolled: 20,
    active: 21,
    completed: 22,
    succeeded: 23,
  },
  unsupportedField: 'bla',
}

export const workflowsCreateResponse = {
  portalId: 62515,
  id: 9274658,
  name: workflowsMock.name,
  updatedAt: 1579426531143,
  insertedAt: 1579426531213,
  type: workflowsMock.type,
  enabled: workflowsMock.enabled,
  description: '',
  contactCounts: {
    active: 0,
    enrolled: 0,
  },
  migrationStatus: {
    portalId: 62515,
    flowId: 7102706,
    workflowId: 5488642,
    migrationStatus: 'EXECUTION_MIGRATED',
    platformOwnsActions: true,
    lastSuccessfulMigrationTimestamp: null,
  },
  originalAuthorUserId: 215482,
  creationSource: {
    sourceApplication: {
      source: 'WORKFLOWS_APP',
      serviceName: 'https://app.hubspot.com/workflows/6962502/platform/create/new',
    },
    createdByUser: {
      userId: 9379192,
      userEmail: 'adam.rosenthal@salto.io',
    },
    createdAt: 1579069732474,
  },
  updateSource: {
    sourceApplication: {
      source: 'WORKFLOWS_APP',
      serviceName: 'https://app.hubspot.com/workflows/6962502/platform/flow/18538464/edit/actions/enrollment/filters',
    },
    updatedByUser: {
      userId: 9379192,
      userEmail: 'adam.rosenthal@salto.io',
    },
    updatedAt: 1579070462059,
    contactListIds: {
      enrolled: 20,
      active: 21,
      completed: 22,
      succeeded: 23,
    },
  },
}

export const workflowsMockArray = [
  firstWorkflowMock,
  secondWorkflowMock,
  workflowsMock,
]


/**
 * MarketingEmail Mock Instances
 */
const firstMarketingEmailMock = {

  ab: true,
  abHoursToWait: 12,
  abVariation: false,
  abSampleSizeDefault: null,
  abSamplingDefault: 'MASTER',
  abStatus: 'MASTER',
  abSuccessMetric: 'OPENS_BY_DELIVERED',
  abTestId: '1234',
  abTestPercentage: 12345,
  absoluteUrl: 'google.com',
  allEmailCampaignIds: [],
  analyticsPageId: 'email ID',
  archived: false,
  author: 'mail@gmail.com',
  authorEmail: 'mail123@gmail.com',
  authorName: 'userName',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  canSpamSettingsId: 'id123',
  clonedFrom: 1234,
  createPage: false,
  created: 12334567,
  currentlyPublished: true,
  domain: 'ynet.com',
  emailBody: 'main email body',
  emailNote: 'email notes',
  emailType: 'AB_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 1234,
  folderId: 999,
  freezeDate: 170456443,
  fromName: 'sender name',
  htmlTitle: 'title',
  id: 111111,
  isGraymailSuppressionEnabled: false,
  isLocalTimezoneSend: false,
  isPublished: true,
  name: 'marketingEmail instance name',
}

const secondMarketingEmailMock = {
  ab: false,
  abHoursToWait: 4,
  abVariation: false,
  abSampleSizeDefault: 'MASTER',
  abSamplingDefault: 'MASTER',
  abStatus: 'VARIANT',
  abSuccessMetric: 'OPENS_BY_DELIVERED',
  abTestId: '1234',
  abTestPercentage: 12345,
  absoluteUrl: 'google.com',
  allEmailCampaignIds: [],
  analyticsPageId: 'email ID',
  archived: false,
  author: 'mail1@gmail.com',
  authorEmail: 'mail13@gmail.com',
  authorName: 'userNameOther',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  canSpamSettingsId: 'id123',
  clonedFrom: 1234,
  createPage: true,
  created: 12334567,
  currentlyPublished: true,
  domain: 'one.com',
  emailBody: 'main body',
  emailNote: 'emails notes',
  emailType: 'ABC_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 1234,
  folderId: 919,
  freezeDate: 170456443,
  fromName: 'sender name',
  htmlTitle: 'title',
  id: 222222,
  isGraymailSuppressionEnabled: true,
  isLocalTimezoneSend: true,
  isPublished: true,
  name: 'marketingEmail instance2 name',
}

const thirdMarketingEmailMock = {
  ab: false,
  abHoursToWait: 11,
  abVariation: false,
  abSampleSizeDefault: 'VARIANT',
  abSamplingDefault: 'MASTER',
  abStatus: 'VARIANT',
  abSuccessMetric: 'OPENS_BY_DELIVERED',
  abTestId: '6543',
  abTestPercentage: 12345,
  absoluteUrl: 'google.com',
  allEmailCampaignIds: [],
  analyticsPageId: 'email ID',
  archived: false,
  author: 'mail,e@gmail.com',
  authorEmail: 'mail134@gmail.com',
  authorName: 'userNameOther1',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  canSpamSettingsId: 'id123',
  clonedFrom: 1234,
  createPage: true,
  created: 12334567,
  currentlyPublished: true,
  domain: 'one.com',
  emailBody: 'main body',
  emailNote: 'emails notes',
  emailType: 'ABC_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 111,
  folderId: 919,
  freezeDate: 170456443,
  fromName: 'sender name',
  htmlTitle: 'title',
  id: 973287,
  isGraymailSuppressionEnabled: true,
  isLocalTimezoneSend: true,
  isPublished: true,
  name: 'marketingEmail instance3 name',
}

export const marketingEmailMock = {
  name: 'newTestMarketingEmail',
  ab: false,
  abHoursToWait: 123,
  abVariation: false,
  abStatus: 'VARIANT',
  archived: false,
  author: 'mail,e@gmail.com',
  authorEmail: 'mail134@gmail.com',
  authorName: 'userNameOther1',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  canSpamSettingsId: 'id123',
  clonedFrom: 1234,
  created: 12334567,
  emailBody: 'main body',
  emailType: 'ABC_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 111,
  folderId: 919,
  freezeDate: 170456443,
  fromName: 'sender name',
  id: 973111,
  isGraymailSuppressionEnabled: true,
  isLocalTimezoneSend: true,
}

export const marketingEmailCreateResponse = {
  name: 'newTestMarketingEmail',
  ab: false,
  abHoursToWait: 123,
  abVariation: false,
  abSampleSizeDefault: null,
  abSamplingDefault: null,
  abStatus: 'VARIANT',
  archived: false,
  author: 'mail,e@gmail.com',
  authorEmail: 'mail134@gmail.com',
  authorName: 'userNameOther1',
  blogEmailType: 'daily',
  campaign: 'campaignID',
  campaignName: 'campaignName',
  canSpamSettingsId: 'id123',
  clonedFrom: 1234,
  createPage: false,
  created: 12334567,
  currentlyPublished: false,
  domain: '',
  emailBody: 'main body',
  emailNote: '',
  emailType: 'ABC_EMAIL',
  feedbackEmailCategory: 'CUSTOM',
  feedbackSurveyId: 111,
  folderId: 919,
  freezeDate: 170456443,
  fromName: 'sender name',
  htmlTitle: '',
  id: 1234566,
  isGraymailSuppressionEnabled: true,
  isLocalTimezoneSend: true,
  isPublished: false,
}

export const marketingEmailMockArray = [
  firstMarketingEmailMock,
  secondMarketingEmailMock,
  thirdMarketingEmailMock,
  marketingEmailMock,
]
