/*
 * Copyright 2025 Salto Labs Ltd.
 * Licensed under the Salto Terms of Use (the "License");
 * You may not use this file except in compliance with the License.  You may obtain a copy of the License at https://www.salto.io/terms-of-use
 *
 * CERTAIN THIRD PARTY SOFTWARE MAY BE CONTAINED IN PORTIONS OF THE SOFTWARE. See NOTICE FILE AT https://github.com/salto-io/salto/blob/main/NOTICES
 */
import {
  ChangeValidator,
  getChangeData,
  isAdditionOrModificationChange,
  isInstanceElement,
  SeverityLevel,
} from '@salto-io/adapter-api'
import { FIELD_TYPE_NAME } from '../../filters/fields/constants'

const PROJECT_TEMPLATE_TO_FIELDS = (): Record<string, string[]> => ({
  'IT Service Management': [
    'Pending_reason__select__c@suuuu',
    'Product_categorization__cascadingselect__c@suuuu',
    'Urgency__select__c',
    'Affected_hardware__textfield__c@suuuu',
    'Approver_groups__multigrouppicker__c@suuuu',
    'Story_Points__float__c@suuuu',
  ],

  'HR Service Management': [
    'Accessibility_needs__textarea__c@suuuu',
    'Case_type__select__c@suuuu',
    'City__textfield__c',
    'Company_email_address__textfield__c@ssuuuu',
    'Date_of_birth__datepicker__c@ssuuuu',
    'Department__select__c',
    'Employee_ID__textfield__c@suuuu',
    'Employee_location__textfield__c@suuuu',
    'Employment_type__select__c@suuuu',
    'End_date__datetime__c@suuuu ',
    'First_name__textfield__c@suuuu',
    'Job_title__textfield__c@suuuu',
    'Last_name__textfield__c@suuuu',
    'Last_working_day__datepicker__c@ssuuuu',
    'Leave_type__select__c@suuuu',
    'Mailing_address__textfield__c@suuuu',
    'Manager__multiuserpicker__c',
    'Middle_name__textfield__c@suuuu',
    'Move_date__datepicker__c@suuuu',
    'Personal_email_address__textfield__c@ssuuuu',
    'Reason__textarea__c',
    'Region__select__c',
    'Residential_status__select__c@suuuu',
    'Resignation_date__datepicker__c@suuuu',
    'Role__textfield__c',
    'Start_date__datetime__c@suuuu',
    'Team__textfield__c',
    'User_picker__multiuserpicker__c@suuuu',
  ],
})

const jsmFieldToTemplateName = (field: string): string | undefined => {
  const map = PROJECT_TEMPLATE_TO_FIELDS()
  return Object.keys(map).find(key => map[key].includes(field))
}

export const systemGeneratedFieldsValidator: ChangeValidator = async changes =>
  changes
    .filter(isAdditionOrModificationChange)
    .map(getChangeData)
    .filter(isInstanceElement)
    .filter(instance => instance.elemID.typeName === FIELD_TYPE_NAME)
    .map(instance => ({
      elemID: instance.elemID,
      templateName: jsmFieldToTemplateName(instance.elemID.name),
    }))
    .filter(({ templateName }) => templateName !== undefined)
    .map(({ elemID, templateName }) => ({
      elemID,
      severity: 'Error' as SeverityLevel,
      message: 'Deploying this field can create duplicate fields in the target environment',
      detailedMessage:
        'The field is auto-generated by Atlassian. To create or modify it in the target environment, create a first project ' +
        `from a template of ${templateName}. For more information, see the documentation at: ` +
        'https://help.salto.io/en/articles/place_holder', // this will change once the article is approved. https://app.intercom.com/a/apps/xbdrirs1/knowledge-hub/all-content?activeContentId=11162442&activeContentType=article&editorMode=edit&types=120
    }))
