/*
*                      Copyright 2021 Salto Labs Ltd.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
import _ from 'lodash'
import { IDENTIFIER_FIELD, TYPE_TO_ID_FIELDS } from './multi_fields_identifiers'

export const ITEM_TYPE_ID = '-10'
export const TRANSACTION_TYPE_ID = '-30'

export const TYPES_TO_INTERNAL_ID: Record<string, string> = {
  Account: '-112',
  AccountingPeriod: '-105',
  AssemblyBuild: TRANSACTION_TYPE_ID,
  AssemblyItem: ITEM_TYPE_ID,
  AssemblyUnbuild: TRANSACTION_TYPE_ID,
  BillingSchedule: '-141',
  Bin: '-242',
  BinTransfer: TRANSACTION_TYPE_ID,
  BinWorksheet: TRANSACTION_TYPE_ID,
  CalendarEvent: '-20',
  Campaign: '-24',
  CampaignResponse: '-130',
  CashRefund: TRANSACTION_TYPE_ID,
  CashSale: TRANSACTION_TYPE_ID,
  Charge: '-290',
  Check: TRANSACTION_TYPE_ID,
  Classification: '-101',
  Contact: '-6',
  ContactCategory: '-158',
  ContactRole: '-157',
  CostCategory: '-155',
  CreditMemo: TRANSACTION_TYPE_ID,
  Currency: '-122',
  Customer: '-2',
  CustomerCategory: '-109',
  CustomerDeposit: TRANSACTION_TYPE_ID,
  CustomerMessage: '-161',
  CustomerPayment: TRANSACTION_TYPE_ID,
  CustomerRefund: TRANSACTION_TYPE_ID,
  CustomerStatus: '-104',
  Department: '-102',
  DepositApplication: TRANSACTION_TYPE_ID,
  DescriptionItem: ITEM_TYPE_ID,
  DiscountItem: ITEM_TYPE_ID,
  DownloadItem: ITEM_TYPE_ID,
  Employee: '-4',
  Estimate: TRANSACTION_TYPE_ID,
  ExpenseCategory: '-126',
  ExpenseReport: TRANSACTION_TYPE_ID,
  GiftCertificateItem: ITEM_TYPE_ID,
  GlobalAccountMapping: '-250',
  InterCompanyJournalEntry: TRANSACTION_TYPE_ID,
  InterCompanyTransferOrder: TRANSACTION_TYPE_ID,
  InventoryAdjustment: TRANSACTION_TYPE_ID,
  InventoryCostRevaluation: TRANSACTION_TYPE_ID,
  InventoryDetail: '-260',
  InventoryItem: ITEM_TYPE_ID,
  InventoryNumber: '-266',
  InventoryTransfer: TRANSACTION_TYPE_ID,
  Invoice: TRANSACTION_TYPE_ID,
  Issue: '-26',
  ItemAccountMapping: '-251',
  ItemDemandPlan: '-246',
  ItemFulfillment: TRANSACTION_TYPE_ID,
  ItemGroup: ITEM_TYPE_ID,
  ItemReceipt: TRANSACTION_TYPE_ID,
  ItemRevision: '-269',
  ItemSupplyPlan: '-247',
  Job: '-7',
  JobType: '-177',
  JournalEntry: TRANSACTION_TYPE_ID,
  KitItem: ITEM_TYPE_ID,
  Location: '-103',
  LotNumberedAssemblyItem: ITEM_TYPE_ID,
  LotNumberedInventoryItem: ITEM_TYPE_ID,
  ManufacturingCostTemplate: '-294',
  ManufacturingOperationTask: '-36',
  ManufacturingRouting: '-288',
  MarkupItem: ITEM_TYPE_ID,
  Note: '-303',
  NoteType: '-180',
  Opportunity: '-31',
  OtherNameCategory: '-181',
  Partner: '-5',
  PartnerCategory: '-182',
  PaycheckJournal: TRANSACTION_TYPE_ID,
  PaymentItem: ITEM_TYPE_ID,
  PaymentMethod: '-183',
  PayrollItem: '-265',
  PhoneCall: '-22',
  PriceLevel: '-186',
  PricingGroup: '-187',
  ProjectTask: '-27',
  PromotionCode: '-121',
  PurchaseOrder: TRANSACTION_TYPE_ID,
  ResourceAllocation: '-28',
  ReturnAuthorization: TRANSACTION_TYPE_ID,
  SalesOrder: TRANSACTION_TYPE_ID,
  SalesRole: '-191',
  SalesTaxItem: '-128',
  SerializedAssemblyItem: ITEM_TYPE_ID,
  SerializedInventoryItem: ITEM_TYPE_ID,
  Solution: '-25',
  Subsidiary: '-117',
  SubtotalItem: ITEM_TYPE_ID,
  SupportCase: '-23',
  Task: '-21',
  Term: '-199',
  TimeBill: '-256',
  TransferOrder: TRANSACTION_TYPE_ID,
  UnitsType: '-201',
  Vendor: '-3',
  VendorBill: TRANSACTION_TYPE_ID,
  VendorCategory: '-110',
  VendorCredit: TRANSACTION_TYPE_ID,
  VendorPayment: TRANSACTION_TYPE_ID,
  VendorReturnAuthorization: TRANSACTION_TYPE_ID,
  WinLossReason: '-203',
  WorkOrder: TRANSACTION_TYPE_ID,
  WorkOrderClose: TRANSACTION_TYPE_ID,
  WorkOrderCompletion: TRANSACTION_TYPE_ID,
  WorkOrderIssue: TRANSACTION_TYPE_ID,
  OtherChargeSaleItem: ITEM_TYPE_ID,
  CheckItem: ITEM_TYPE_ID,
  CustomSaleItem: ITEM_TYPE_ID,
  CustomPurchaseItem: ITEM_TYPE_ID,
  OpportunityItem: ITEM_TYPE_ID,
  SalesOrderItem: ITEM_TYPE_ID,
  ItemFulfillmentItem: ITEM_TYPE_ID,
  InvoiceItem: ITEM_TYPE_ID,
  CashSaleItem: ITEM_TYPE_ID,
  EstimateItem: ITEM_TYPE_ID,
  TransferOrderItem: ITEM_TYPE_ID,
  InterCompanyTransferOrderItem: ITEM_TYPE_ID,
  WorkOrderItem: ITEM_TYPE_ID,
  BinWorksheetItem: ITEM_TYPE_ID,
  CashRefundItem: ITEM_TYPE_ID,
  ReturnAuthorizationItem: ITEM_TYPE_ID,
  CreditMemoItem: ITEM_TYPE_ID,
  VendorBillItem: ITEM_TYPE_ID,
  PurchaseOrderItem: ITEM_TYPE_ID,
  ItemReceiptItem: ITEM_TYPE_ID,
  VendorCreditItem: ITEM_TYPE_ID,
  VendorReturnAuthorizationItem: ITEM_TYPE_ID,
  PurchaseRequisitionItem: ITEM_TYPE_ID,
  NonInventoryPurchaseItem: ITEM_TYPE_ID,
  NonInventorySaleItem: ITEM_TYPE_ID,
  NonInventoryResaleItem: ITEM_TYPE_ID,
  OtherChargeResaleItem: ITEM_TYPE_ID,
  OtherChargePurchaseItem: ITEM_TYPE_ID,
  ServiceResaleItem: ITEM_TYPE_ID,
  ServicePurchaseItem: ITEM_TYPE_ID,
  ServiceSaleItem: ITEM_TYPE_ID,
  TaxGroupTaxItem: ITEM_TYPE_ID,
  PresentationItem: ITEM_TYPE_ID,
  TimeItem: ITEM_TYPE_ID,
}

export const INTERNAL_ID_TO_TYPES: Record<string, string[]> = _(TYPES_TO_INTERNAL_ID)
  .entries()
  .groupBy(([_type, internalId]) => internalId)
  .mapValues(values => values.map(([type]) => type))
  .value()

export const ITEM_TYPE_TO_SEARCH_STRING: Record<string, string> = {
  AssemblyItem: '_assembly',
  LotNumberedAssemblyItem: '_assembly',
  SerializedAssemblyItem: '_assembly',
  DescriptionItem: '_description',
  DiscountItem: '_discount',
  KitItem: '_kit',
  MarkupItem: '_markup',
  NonInventoryPurchaseItem: '_nonInventoryItem',
  NonInventorySaleItem: '_nonInventoryItem',
  NonInventoryResaleItem: '_nonInventoryItem',
  OtherChargeSaleItem: '_otherCharge',
  OtherChargeResaleItem: '_otherCharge',
  OtherChargePurchaseItem: '_otherCharge',
  PaymentItem: '_payment',
  ServiceResaleItem: '_service',
  ServicePurchaseItem: '_service',
  ServiceSaleItem: '_service',
  SubtotalItem: '_subtotal',
  InventoryItem: '_inventoryItem',
  LotNumberedInventoryItem: '_inventoryItem',
  SerializedInventoryItem: '_inventoryItem',
  ItemGroup: '_itemGroup',
  GiftCertificateItem: '_giftCertificateItem',
  DownloadItem: '_downloadItem',
}

export const TYPE_TO_IDENTIFIER: Record<string, string> = {
  Account: 'acctName',
  Subsidiary: 'name',
  Department: 'name',
  Classification: 'name',
  Location: 'name',
  Currency: 'name',
  Customer: 'entityId',
  Employee: 'entityId',
  Job: 'entityId',
  ManufacturingCostTemplate: 'name',
  Partner: 'partnerCode',
  Solution: 'solutionCode',
  ...Object.fromEntries(Object.keys(ITEM_TYPE_TO_SEARCH_STRING).map(type => [type, 'itemId'])),
  ...Object.fromEntries(Object.keys(TYPE_TO_ID_FIELDS).map(type => [type, IDENTIFIER_FIELD])),
}

export const SUPPORTED_TYPES = Object.keys(TYPES_TO_INTERNAL_ID)
