/*
*                      Copyright 2020 Salto Labs Ltd.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
import { ElemID } from '@salto-io/adapter-api'

export const OBJECT_TYPES = [
  'Account',
  'Activity',
  'Asset',
  'AssetRelationship',
  'AssignedResource',
  'AssociatedLocation',
  'AuthorizationForm',
  'AuthorizationFormConsent',
  'AuthorizationFormDataUse',
  'AuthorizationFormText',
  'Campaign',
  'CampaignMember',
  'CardPaymentMethod',
  'Case',
  'CommSubscription',
  'CommSubscriptionChannelType',
  'CommSubscriptionConsent',
  'CommSubscriptionTiming',
  'ConsumptionRate',
  'ConsumptionSchedule',
  'Contact',
  'ContactPointAddress',
  'ContactPointConsent',
  'ContactPointEmail',
  'ContactPointPhone',
  'ContactPointTypeConsent',
  'ContactRequest',
  'ContentVersion',
  'Contract',
  'CreditMemo',
  'CreditMemoLine',
  'DandBCompany',
  'DataUseLegalBasis',
  'DataUsePurpose',
  'DigitalWallet',
  'DuplicateRecordItem',
  'DuplicateRecordSet',
  'EmailMessage',
  'EngagementChannelType',
  'Event',
  'Image',
  'Individual',
  'Invoice',
  'InvoiceLine',
  'Lead',
  'ListEmail',
  'Location',
  'Macro',
  'MessagingSession',
  'MessagingEndUser',
  'OperatingHours',
  'Opportunity',
  'OpportunityContactRole',
  'OpportunityLineItem',
  'Order',
  'OrderItem',
  'PartyConsent',
  'Payment',
  'PaymentAuthorization',
  'PaymentGateway',
  'PaymentGroup',
  'PaymentLineInvoice',
  'Pricebook2',
  'PricebookEntry',
  'ProcessException',
  'Product2',
  'ProductConsumptionSchedule',
  'LocationWaitlist',
  'LocWaitlistMsgTemplate',
  'LocationWaitlistedParty',
  'QuickText',
  'Recommendation',
  'Refund',
  'RefundLinePayment',
  'ResourceAbsence',
  'ResourcePreference',
  'ReturnOrder',
  'ReturnOrderItemAdjustment',
  'ReturnOrderItemTax',
  'ReturnOrderLineItem',
  'Scorecard',
  'ScorecardAssociation',
  'ScorecardMetric',
  'ServiceAppointment',
  'ServiceResource',
  'ServiceResourceSkill',
  'ServiceTerritory',
  'ServiceTerritoryMember',
  'ServiceTerritoryWorkType',
  'SkillRequirement',
  'SocialPersona',
  'Task',
  'TimeSlot',
  'User',
  'UserProvisioningRequest',
  'WorkType',
  'WorkTypeGroup',
  'WorkTypeGroupMember',
]

export const GENERAL_URLS_MAP: Record<string, string> = {
  [new ElemID('salesforce', 'PermissionSet').getFullName()]: 'lightning/setup/PermSets/home',
  [new ElemID('salesforce', 'PermissionSetGroup').getFullName()]: 'lightning/setup/PermSetGroups/home',
  [new ElemID('salesforce', 'ApexClass').getFullName()]: 'lightning/setup/ApexClasses/home',
  [new ElemID('salesforce', 'Flow').getFullName()]: 'lightning/setup/Flows/home',
  [new ElemID('salesforce', 'Holidays').getFullName()]: 'lightning/setup/Holiday/home',
  [new ElemID('salesforce', 'Profile').getFullName()]: 'lightning/setup/EnhancedProfiles/home',
  [new ElemID('salesforce', 'CustomMetadata').getFullName()]: 'lightning/setup/CustomMetadata/home',
  [new ElemID('salesforce', 'CustomPermission').getFullName()]: 'lightning/setup/CustomPermissions/home',
  [new ElemID('salesforce', 'ApexComponent').getFullName()]: 'lightning/setup/ApexComponents/home',
  [new ElemID('salesforce', 'ApexPage').getFullName()]: 'lightning/setup/ApexPages/home',
  [new ElemID('salesforce', 'EmailTemplate').getFullName()]: 'lightning/setup/CommunicationTemplatesEmail/home',
  [new ElemID('salesforce', 'ReportType').getFullName()]: 'lightning/setup/CustomReportTypes/home',
  [new ElemID('salesforce', 'AnalyticSnapshot').getFullName()]: 'lightning/setup/AnalyticSnapshots/home',
  [new ElemID('salesforce', 'ApexTrigger').getFullName()]: 'lightning/setup/ApexTriggers/home',
  [new ElemID('salesforce', 'AssignmentRules', 'instance', 'Lead').getFullName()]: 'lightning/setup/LeadRules/home',
  [new ElemID('salesforce', 'AssignmentRules', 'instance', 'Case').getFullName()]: 'lightning/setup/CaseRules/home',
  [new ElemID('salesforce', 'Queue').getFullName()]: 'lightning/setup/Queues/home',
  [new ElemID('salesforce', 'LightningComponentBundle').getFullName()]: 'lightning/setup/LightningComponentBundles/home',
  [new ElemID('salesforce', 'Report').getFullName()]: 'lightning/o/Report/home',
  [new ElemID('salesforce', 'Dashboard').getFullName()]: 'lightning/o/Dashboard/home',
}

export const SETTINGS_URLS_MAP: Record<string, string> = {
  [new ElemID('salesforce', 'BusinessHoursSettings').getFullName()]: 'lightning/setup/BusinessHours/home',
  [new ElemID('salesforce', 'LanguageSettings').getFullName()]: 'lightning/setup/LanguageSettings/home',
  [new ElemID('salesforce', 'MyDomainSettings').getFullName()]: 'lightning/setup/OrgDomain/home',
  [new ElemID('salesforce', 'ApexSettings').getFullName()]: 'lightning/setup/ApexSettings/home',
}
