#! /usr/bin/env node

const { execSync } = require('child_process')
const { readFileSync, writeFileSync, existsSync, readdirSync } = require('fs')
const path = require('path')


function main() {
  const continueConfigFilePath = path.join(__dirname, '..', 'continue_config.yml')
  const configTemplate = readFileSync(path.join(__dirname, '..', 'config_template.yml'), 'utf8')

  const e2ePackagesToTest = readFileSync(path.join(__dirname, '..', 'e2e_packages_to_test.txt'), 'utf8').split('\n').filter(Boolean)
  console.log('e2ePackagesToTest:', e2ePackagesToTest)

  const e2eTestMatrix = `
      - test_e2e:
          requires:
            - build
          matrix:
            parameters:
              package_name:
                - ${e2ePackagesToTest.join('\n                - ')}`


  let alteredConfigTemplate = e2ePackagesToTest.length > 0 ? 
              configTemplate.replace(/# <NEEDS_E2E_TEST_REQUIREMENT>/g, '- test_e2e')
                            .replace(/# <TEST_MATRIX_E2E>/g, e2eTestMatrix) 
            : configTemplate.replace(/# <NEEDS_E2E_TEST_REQUIREMENT>/g, '')
                            .replace(/# <TEST_MATRIX_E2E>/g, '')
  
  writeFileSync(continueConfigFilePath, alteredConfigTemplate)
  console.log(alteredConfigTemplate)
}

main()
