/*
*                      Copyright 2023 Salto Labs Ltd.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

type ValidPermissionLevels = 'None' | 'View' | 'Create' | 'Edit' | 'Full'

export const ID_TO_PERMISSION_INFO: Record<string, Set<ValidPermissionLevels>> = {
  ADMI_ACCOUNTING: new Set(['None', 'Full']),
  ADMI_ACCOUNTINGBOOK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_ACCOUNTINGLIST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_ACCTPERIODS: new Set(['None', 'View', 'Full']),
  ADMI_ACCTSETUP: new Set(['None', 'Full']),
  ADMI_ADMINDOCSEU: new Set(['None', 'Full']),
  ADMI_ADMINDOCSNA: new Set(['None', 'Full']),
  ADMI_ADMINDOCSOTHER: new Set(['None', 'Full']),
  ADMI_ACH: new Set(['None', 'Full']),
  ADMI_ADVANCED_ORDER_MANAGEMENT: new Set(['None', 'Full']),
  ADMI_ADVANCED_TEMPLATES: new Set(['None', 'Full']),
  ADMI_ALLOW_JS_HTML_UPLOAD: new Set(['None', 'Full']),
  ADMI_ALLOWNONGLCHANGES: new Set(['None', 'Full']),
  ADMI_ANALYTICS: new Set(['None', 'Full']),
  ADMI_APP_DEPLOYMENT: new Set(['None', 'Full']),
  ADMI_APPDEFPKG: new Set(['None', 'Full']),
  ADMI_APPPUBLISHER: new Set(['None', 'Full']),
  ADMI_AUDITLOGIN: new Set(['None', 'Full']),
  ADMI_BACKUPEXPORT: new Set(['None', 'Full']),
  ADMI_BALANCE_TRX_BY_SEGMENTS: new Set(['None', 'View', 'Create']),
  ADMI_BANK_CONNECTIVITY_CONFIG: new Set(['None', 'Full']),
  ADMI_BILLINGINFO: new Set(['None', 'Full']),
  ADMI_BILLPAYSETUP: new Set(['None', 'Full']),
  ADMI_BLCGA: new Set(['None', 'Full']),
  ADMI_BUNDLER: new Set(['None', 'Full']),
  ADMI_BUNDLERAUDITTRAIL: new Set(['None', 'Full']),
  ADMI_BUNDLERMANUP: new Set(['None', 'Full']),
  ADMI_CAMPAIGNEMAIL: new Set(['None', 'Full']),
  ADMI_CAMPAIGNSETUP: new Set(['None', 'Full']),
  ADMI_CASEALERT: new Set(['None', 'View', 'Full']),
  ADMI_CASEFORM: new Set(['None', 'Full']),
  ADMI_CASEISSUE: new Set(['None', 'Full']),
  ADMI_CASEORIGIN: new Set(['None', 'Full']),
  ADMI_CASEPRIORITY: new Set(['None', 'Full']),
  ADMI_CASERULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CASESTATUS: new Set(['None', 'Full']),
  ADMI_CASETERRITORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CASETYPE: new Set(['None', 'Full']),
  ADMI_CENTERLINK: new Set(['None', 'Full']),
  ADMI_CERTIFICATES: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CLASSESTOLOCS: new Set(['None', 'Full']),
  ADMI_CLASSSEGMENTMAPPING: new Set(['None', 'Full']),
  ADMI_CLOSEPERIOD: new Set(['None', 'Full']),
  ADMI_COMMERCECATEGORY: new Set(['None', 'Full']),
  ADMI_COMMISSIONSETUP: new Set(['None', 'Full']),
  ADMI_COMPANY: new Set(['None', 'Full']),
  ADMI_CONVERTCLASSES: new Set(['None', 'Full']),
  ADMI_CONVERTLEAD: new Set(['None', 'Full']),
  ADMI_COPYPROJECTTASK: new Set(['None', 'Full']),
  ADMI_CREATEJOBSFROMSALESTRANS: new Set(['None', 'Full']),
  ADMI_CREDITCARD: new Set(['None', 'Full']),
  ADMI_CRMLIST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CROSSCHARGE: new Set(['View', 'None', 'Full']),
  ADMI_CSVIMPORTPREF: new Set(['None', 'Full']),
  ADMI_CUSTADDRESSFORM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTBODYFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTCATEGORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTCENTER: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTCOLUMNFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTEMAILLAYOUT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTENTITYFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTENTRYFORM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTEVENTFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTFIELDTAB: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTFORM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTITEMFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTITEMNUMBERFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTLAYOUT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTLIST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTOMERFORM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTOMERRULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTOMER_SEGMENTS: new Set(['None', 'Full']),
  ADMI_CUSTOMIZEDFIELDLEVELHELP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTOMSCRIPT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTOMSUBLIST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTOTHERFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTRECORD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTRECORDFORM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTSECTION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTTASKS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTTRANFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_CUSTTRANSACTION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_DELETEDRECORD: new Set(['None', 'Full']),
  ADMI_DEPTSEGMENTMAPPING: new Set(['None', 'Full']),
  ADMI_DEVICE_ID: new Set(['None', 'Full']),
  ADMI_DOMAINS: new Set(['None', 'Full']),
  ADMI_DUPLICATESETUP: new Set(['None', 'Full']),
  ADMI_EMPLCATEGORY: new Set(['None', 'Full']),
  ADMI_EMPLOYEE_EXPENSE_SOURCE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_EMPLOYEECENTERPUBLISHING: new Set(['None', 'Full']),
  ADMI_EMPLOYEELIST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_ENABLEFEATURES: new Set(['None', 'Full']),
  ADMI_ENTITYACCOUNTMAPPING: new Set(['None', 'Full']),
  ADMI_ENTITYSTATUS: new Set(['None', 'Full']),
  ADMI_ESCALATIONRULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_ESCALATIONTERRITORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_EXPENSEREPORTPOLICY: new Set(['None', 'View', 'Full']),
  ADMI_EXPORTIIF: new Set(['None', 'Full']),
  ADMI_FFTEXCEPTIONREASON: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_FINANCIALINSTITUTION: new Set(['None', 'Full']),
  ADMI_FINCHARGEPREF: new Set(['None', 'Full']),
  ADMI_GAINLOSSACCTMAPPING: new Set(['None', 'Full']),
  ADMI_GLOBALACCOUNTMAPPING: new Set(['None', 'Full']),
  ADMI_IMPORTCSVFILE: new Set(['None', 'Full']),
  ADMI_IMPORTOVERRIDESSTRIG: new Set(['None', 'Full']),
  ADMI_IMPORTXML: new Set(['None', 'Full']),
  ADMI_INTEGRAPP: new Set(['None', 'Full']),
  ADMI_ISSUESETUP: new Set(['None', 'Full']),
  ADMI_ISSUESHOWSTOPPER: new Set(['None', 'Full']),
  ADMI_ITEMACCOUNTMAPPING: new Set(['None', 'Full']),
  ADMI_KERNEL: new Set(['None', 'Full']),
  ADMI_KEYS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_KNOWLEDGEBASE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_KPIREPORT: new Set(['None', 'Full']),
  ADMI_LOCATIONCOSTINGGROUP: new Set(['None', 'Full']),
  ADMI_LOCSEGMENTMAPPING: new Set(['None', 'Full']),
  ADMI_LOGIN_OAUTH: new Set(['None', 'Full']),
  ADMI_LOGIN_OAUTH2: new Set(['None', 'Full']),
  ADMI_MANAGECUSTOMSEGMENTS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_MANAGE_OAUTH2: new Set(['None', 'Full']),
  ADMI_MANAGE_OAUTH_TOKENS: new Set(['None', 'Full']),
  ADMI_MANAGE_OWN_OAUTH_TOKENS: new Set(['None', 'Full']),
  ADMI_MANAGE_RESTRICTIONS: new Set(['None', 'View', 'Edit', 'Full', 'Create']),
  ADMI_MANAGEPERMISSIONS: new Set(['None', 'Full']),
  ADMI_MANAGEROLES: new Set(['None', 'Full']),
  ADMI_MANAGEUSERS: new Set(['None', 'Full']),
  ADMI_MANUFACTURING: new Set(['None', 'Full']),
  ADMI_MHLEVEL: new Set(['None', 'Full']),
  ADMI_MHNODE: new Set(['None', 'Full']),
  ADMI_MHVERSION: new Set(['None', 'Full']),
  ADMI_MIGRATEREVARRNGANDPLAN: new Set(['None', 'Full']),
  ADMI_MOBILE_ACCESS: new Set(['None', 'Full']),
  ADMI_NSASOIDCPROVIDER: new Set(['None', 'Full']),
  ADMI_NUMBERING: new Set(['None', 'View', 'Edit', 'Full']),
  ADMI_OIDC: new Set(['None', 'Full']),
  ADMI_OIDCSETUP: new Set(['None', 'Full']),
  ADMI_OPENIDSSO: new Set(['None', 'Full']),
  ADMI_OPENIDSSOSETUP: new Set(['None', 'Full']),
  ADMI_ORDERALLOCATIONSTRATEGY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_ORDERPROMISING: new Set(['None', 'View', 'Full']),
  ADMI_OUTLOOKINTEGRATION: new Set(['None', 'Full']),
  ADMI_OUTLOOKINTEGRATION_V3: new Set(['None', 'Full']),
  ADMI_PARTNERCONTRIBUTION: new Set(['None', 'Full']),
  ADMI_PAYMENT_LINK_SETUP: new Set(['None', 'Full']),
  ADMI_PAYROLL: new Set(['None', 'Full']),
  ADMI_PENDINGBOOKJOURNAL: new Set(['None', 'Full']),
  ADMI_PERIODCLOSING: new Set(['None', 'Full']),
  ADMI_PERIODOVERRIDE: new Set(['None', 'Full']),
  ADMI_PI_REMOVAL_CREATE: new Set(['None', 'Full']),
  ADMI_PI_REMOVAL_RUN: new Set(['None', 'Full']),
  ADMI_PROJECT_ACCOUNTING_SETUP: new Set(['None', 'Full']),
  ADMI_PROVISION: new Set(['None', 'View', 'Full']),
  ADMI_REPOGROUPS: new Set(['None', 'Full']),
  ADMI_REPOLAYOUTS: new Set(['None', 'Full']),
  ADMI_RESTWEBSERVICES: new Set(['None', 'Full']),
  ADMI_REVIEW_CUSTOM_GL_RUNS: new Set(['None', 'Full']),
  ADMI_SALESCHANNEL: new Set(['None', 'View', 'Edit', 'Full', 'Create']),
  ADMI_SALESTERRITORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_SAMLSSO: new Set(['None', 'Full']),
  ADMI_SAMLSSOSETUP: new Set(['None', 'Full']),
  ADMI_SAVEDASHBOARD: new Set(['None', 'Full']),
  ADMI_SETUPCOMPANY: new Set(['None', 'View', 'Full']),
  ADMI_SETUPIMAGERESIZE: new Set(['None', 'Full']),
  ADMI_SETUPYEARSTATUS: new Set(['None', 'Full']),
  ADMI_SFASETUP: new Set(['None', 'Full']),
  ADMI_SITEMANAGEMENT: new Set(['None', 'Full']),
  ADMI_STATETAXIMPORT: new Set(['None', 'Full']),
  ADMI_STORESEARCH: new Set(['None', 'Full']),
  ADMI_STORESETUP: new Set(['None', 'Full']),
  ADMI_SUBLIST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_SUBSIDIARYHIERARCHYMOD: new Set(['None', 'View', 'Edit']),
  ADMI_SUBSIDIARYSETTINGSMANAGER: new Set(['None', 'View', 'Edit']),
  ADMI_SUITE_OAX_CONNECTOR: new Set(['None', 'Full']),
  ADMI_SUITEANALYTICSCONNECT: new Set(['None', 'Full']),
  ADMI_SUITEAPP_MANAGEMENT: new Set(['None', 'Full']),
  ADMI_SUITECOMMERCEANALYTICS: new Set(['None', 'View', 'Full']),
  ADMI_SUITESIGNON: new Set(['None', 'Full']),
  ADMI_SUPPLYALLOCATIONSETUP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  ADMI_SUPPORTSETUP: new Set(['None', 'Full']),
  ADMI_SWAPPRICES: new Set(['None', 'Full']),
  ADMI_TAXMIGRATION: new Set(['None', 'Full']),
  ADMI_TIMEMODIFICATION: new Set(['None', 'Full']),
  ADMI_TAXPERIODS: new Set(['None', 'Full']),
  ADMI_TEAMSELLINGCONTRIBUTION: new Set(['None', 'Full']),
  ADMI_TELEPHONY_SETUP: new Set(['None', 'Full']),
  ADMI_TRAN_ACCOUNTING_RULES: new Set(['None', 'Full']),
  ADMI_TRANSITEMTXT: new Set(['None', 'Full']),
  ADMI_TRANSLATION: new Set(['None', 'Full']),
  ADMI_TSTDRV_MASTER: new Set(['None', 'Full']),
  ADMI_TWOFACTORAUTH: new Set(['None', 'Full']),
  ADMI_TWOFACTORAUTHBASE: new Set(['None', 'Full']),
  ADMI_UNCATSITEITEMS: new Set(['None', 'Full']),
  ADMI_UPDATEPRICES: new Set(['None', 'Full']),
  ADMI_UPSELLSETUP: new Set(['None', 'Full']),
  ADMI_WEBSERVICES: new Set(['None', 'Full']),
  ADMI_WEBSERVICESLOG: new Set(['None', 'Full']),
  ADMI_WEBSERVICESSETUP: new Set(['None', 'Full']),
  ADMI_WORKFLOW: new Set(['None', 'Full']),
  ADMINDOCS: new Set(['None', 'Full']),
  LIST_ACCOUNT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ACH: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ALLGOVERNMENTISSUEDIDS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ALLOCSCHEDULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_AMORTIZATION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_BASICGOVERNMENTISSUEDIDS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_BIG_SEARCH: new Set(['None', 'Create']),
  LIST_BILLINBOUNDSHIPMENT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_BILLINGSCHEDULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_BILLOFDISTRIBUTION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_BILLOFMATERIALSINQUIRY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_BOM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_BILLCAPTURE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_BIN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_BONUS: new Set(['View', 'None', 'Create', 'Full', 'Edit']),
  LIST_BONUSTYPE: new Set(['View', 'None', 'Create', 'Full', 'Edit']),
  LIST_CALENDAR: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CALL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CAMPAIGN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CAMPAIGNHISTORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CARDHOLDERAUTHENTICATION: new Set(['None', 'View', 'Edit', 'Full', 'Create']),
  LIST_CARDHOLDERAUTHEVENT: new Set(['None', 'View', 'Edit', 'Full', 'Create']),
  LIST_CASE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CASE_DUPLICATES: new Set(['None', 'Full']),
  LIST_CATEGORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CERTIFICATES: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CHECKITEMAVAILABILITY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CLASS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_COLORTHEME: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_COMMISSIONRULES: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_COMPANY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_COMPETITOR: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_COMPONENTWHEREUSEDINQUIRY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CONTACT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CONTACTROLE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CONVERTLEAD: new Set(['View', 'None', 'Create', 'Full', 'Edit']),
  LIST_COSTEDBOMINQUIRY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CRMGROUP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CRMMESSAGE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CRMTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CURRENCY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CUSTJOB: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CUSTPROFILE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_CUSTRECORDENTRY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_DEPARTMENT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_DISTRIBUTIONNETWORK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EARLIEST_AVAILABILITY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMAILTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEE_ACCESS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEE_ADMINISTRATION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEE_CONFIDENTIAL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEE_PUBLIC: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEE_RECORD: new Set(['View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEE_SELF: new Set(['View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEECHANGETYPE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEECHANGEREASON: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEECHANGEREQUEST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEEEFFECTIVEDATING: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEESEPARATION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EMPLOYEESSN: new Set(['None', 'View', 'Full']),
  LIST_ENTITY_DUPLICATES: new Set(['None', 'View', 'Full']),
  LIST_EVENT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EXPENSEAMORTIZATIONRULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EXPENSEPLAN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_EXPORT: new Set(['None', 'Create']),
  LIST_FAIRVALUEDIMENSION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_FAIRVALUEFORMULA: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_FAIRVALUEPRICE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_FAXMESSAGE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_FAXTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_FILECABINET: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_FIND: new Set(['None', 'View', 'Full']),
  LIST_FINHISTORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_FISCALCALENDAR: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_GENERAL_TOKEN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_GENERICRESOURCE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_GLLINESAUDITLOG: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_GLLINESAUDITLOGSEG: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_GLOBALINVTRELATIONSHIP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_GOVERNMENTISSUEDIDTYPE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_HCMJOB: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_HCMPOSITION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_HISTORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_IMPORTED_EMPLOYEE_EXPENSE: new Set(['View', 'None']),
  LIST_INBOUNDSHIPMENT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_INFOCATEGORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_INFOITEM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_INFOITEMFORM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_INTEGRAPP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_INTERNALPUBLISH: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_INVCOSTTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_INVENTORYSTATUS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ISSUE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ITEM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ITEM_COLLECTION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ITEMDEMANDPLAN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ITEMREVENUECATEGORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ITEMPROCESSFAMILY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ITEMPROCESSGROUP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ITEM_REVISION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ITEMSUPPLYPLAN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ITEMTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_JOB: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_JOBREQUISITION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_KEYS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_KUDOS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_KNOWLEDGEBASE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_LABORCOSTING: new Set(['View', 'None', 'Full', 'Create', 'Edit']),
  LIST_LOCATION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_MAILMERGE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_MAILMESSAGE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_MAILTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_MASSUPDATES: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_MATERIALREQUIREMENTSPLAN: new Set(['View', 'None', 'Full', 'Create', 'Edit']),
  LIST_MEDIAITEMFOLDER: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_MEMDOC: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_MFGCOSTTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_MFGROUTING: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_NEWSITEM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_NOTIFICATION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ONBOARDING_PLAN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ORDER_REALLOCATION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ORDERMANAGEDASHBOARD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ORGANIZATIONVALUE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_OTHERNAME: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_OUTBOUNDREQUEST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_OVERTIMEPOLICY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PARTNER: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PARTNERCOMMISSNRULES: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PAYCHECK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PAYMENT_CARD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PAYMENT_CARD_TOKEN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PAYMENT_INSTRUMENTS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PAYMETH: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PAYROLLITEM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PDFMESSAGE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PDFTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PHASEDPROCESS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PICKSTRATEGY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PICKTASK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PLANNEDREVENUE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PLANNEDSTANDARDCOST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PRESCATEGORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PRICEBOOK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PRICEPLAN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PROJECT_BUDGET: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PROJECTREVENUERULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PROJECTTASK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PROJECTTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PROMOTIONCODE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_PUBLISHSEARCH: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_QUANTITYPRICINGSCHEDULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_REALLOCATE_ORDER_ITEM: new Set(['View', 'None', 'Full', 'Create', 'Edit']),
  LIST_RECOGNITIONEVENTTYPE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_RECORDCUSTFIELD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_RELATEDITEMS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_RESOURCE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_RESOURCEGROUP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_REVENUEELEMENT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_REVENUEPLAN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_REVENUERECOGNITIONRULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_REVRECSCHEDULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_REVRECTREATMENT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_REVRECTREATMENTRULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_REVRECFIELDMAPPING: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_REVRECVSOE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_RSRCALLOCATION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_RSRCALLOCATIONAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_RSSFEED: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SALESCAMPAIGN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SALESROLE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SCSNAPSHOT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SENTEMAIL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SHIPITEM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SHIPPARTPACKAGE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SHIPPARTREGISTRATION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SHIPPARTSHIPMENT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SHORTCUT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SCHEDULEMASSUPDATES: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SITEEMAILTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_STANDARDCOSTVERSION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_STORECATEGORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_STOREITEMLISTLA: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_STORETAB: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SUBSCRIPTION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SUBSCRIPTIONCHANGEORDER: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SUBSCRIPTIONPLAN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SUBSIDIARY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SUPPLY_REALLOCATION: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_SYSTEMEMAILTEMPLATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_TALENT_ADMINISTRATION: new Set(['View', 'Full']),
  LIST_TASK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_TAXDETAILSTAB: new Set(['None', 'View', 'Edit', 'Full']),
  LIST_TAXENGINESELECTION: new Set(['None', 'View', 'Edit', 'Full']),
  LIST_TAXITEM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_TAXSCHEDULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_TEGATAACCOUNT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_TEMPLATE_CATEGORY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_TIMECODE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_TIMEOFFADMIN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_TRANNUMBERAUDITLOG: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_UNDELIVEREDEMAIL: new Set(['None', 'View']),
  LIST_UNIT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_UPSELL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_UPSELLWIZARD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_USAGE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_VENDOR: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_WBS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_WEBSITE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_WORKASSIGNMENT: new Set(['View', 'None', 'Full', 'Create', 'Edit']),
  LIST_WORKCALENDAR: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_WORKPLACE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  LIST_ZONE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_ACCTPAY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_ACCTREC: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_BANK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_COGS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_CREDCARD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_DEFEREXPENSE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_DEFERREVENUE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_EQUITY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_EXPENSE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_FIXEDASSET: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_INCOME: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_LONGTERMLIAB: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_NONPOSTING: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_OTHASSET: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_OTHCURRASSET: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_OTHCURRLIAB: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_OTHEXPENSE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_OTHINCOME: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_PAYROLL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_STAT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REGT_UNBILLEDREC: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REPO_1099: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REPO_940: new Set(['None', 'View']),
  REPO_941: new Set(['None', 'View']),
  REPO_ACCOUNTDETAIL: new Set(['None', 'View']),
  REPO_AMORTIZATION: new Set(['None', 'View']),
  REPO_ANALYTICS: new Set(['None', 'Edit']),
  REPO_AP: new Set(['None', 'View']),
  REPO_AR: new Set(['None', 'View']),
  REPO_AUTHPARTNERCOMMISSION: new Set(['None', 'View']),
  REPO_BALANCESHEET: new Set(['None', 'View']),
  REPO_BOOKINGS: new Set(['None', 'View']),
  REPO_BUDGET: new Set(['None', 'View']),
  REPO_CASHFLOW: new Set(['None', 'View']),
  REPO_COMMISSION: new Set(['None', 'View']),
  REPO_CUSTOMIZATION: new Set(['None', 'View']),
  REPO_DEFERREDEXPENSE: new Set(['None', 'View']),
  REPO_FINANCIALS: new Set(['None', 'View']),
  REPO_GL: new Set(['None', 'View']),
  REPO_GRANT_ACCESS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REPO_GSTSUMMARY: new Set(['None', 'View']),
  REPO_INTEGRATION: new Set(['None', 'View']),
  REPO_INVENTORY: new Set(['None', 'View']),
  REPO_ISSUE: new Set(['None', 'View']),
  REPO_MARKETING: new Set(['None', 'View']),
  REPO_NONPOSTING: new Set(['None', 'View']),
  REPO_PANDL: new Set(['None', 'View']),
  REPO_PARTNERCOMMISSION: new Set(['None', 'View']),
  REPO_PAYCHECKDETAIL: new Set(['None', 'View']),
  REPO_PAYROLL: new Set(['None', 'View']),
  REPO_PAYROLLHIDEFINEMPINFO: new Set(['None', 'View']),
  REPO_PAYROLLHOURSEARNING: new Set(['None', 'View']),
  REPO_PAYROLLJOURNAL: new Set(['None', 'View']),
  REPO_PAYROLLLIAB: new Set(['None', 'View']),
  REPO_PAYROLLSTATEWITHHOLD: new Set(['None', 'View']),
  REPO_PAYROLLW2: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  REPO_PERIODENDFINANCIALS: new Set(['None', 'View']),
  REPO_PROJECT_ACCOUNTING: new Set(['None', 'View']),
  REPO_PSTSUMMARY: new Set(['None', 'View']),
  REPO_PURCHASEORDER: new Set(['None', 'View']),
  REPO_PURCHASES: new Set(['None', 'View']),
  REPO_QUOTA: new Set(['None', 'View']),
  REPO_RECONCILE: new Set(['None', 'View']),
  REPO_REMINDEREMPLOYEE: new Set(['None', 'View']),
  REPO_RETURNAUTH: new Set(['None', 'View']),
  REPO_REVREC: new Set(['None', 'View']),
  REPO_RSRCALLOCATION: new Set(['None', 'View']),
  REPO_SALES: new Set(['None', 'View']),
  REPO_SALESORDER: new Set(['None', 'View']),
  REPO_SALES_PARTNER: new Set(['None', 'View']),
  REPO_SALES_PROMO: new Set(['None', 'View']),
  REPO_SCHEDULE: new Set(['None', 'Full']),
  REPO_SNAPSHOTCASE: new Set(['None', 'View']),
  REPO_SNAPSHOTLEAD: new Set(['None', 'View']),
  REPO_SFA: new Set(['None', 'View']),
  REPO_SUPPORT: new Set(['None', 'View']),
  REPO_TAX: new Set(['None', 'View']),
  REPO_TAXREPORTS: new Set(['None', 'View']),
  REPO_TIME: new Set(['None', 'View']),
  REPO_TRAN: new Set(['None', 'View']),
  REPO_TRIALBALANCE: new Set(['None', 'View']),
  REPO_UNBILLED: new Set(['None', 'View']),
  REPO_W4: new Set(['None', 'View']),
  REPO_WEBSITE: new Set(['None', 'View']),
  REPO_WEBSTORE: new Set(['None', 'View']),
  REPO_WORKFORCEANALYTICS: new Set(['View']),
  TRAN_ADJUSTMENTJOURNAL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_ALLOCSCHEDULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_AMENDW4: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_APPROVECOMMISSN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_APPROVEDD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_APPROVEEFT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_APPROVEPARTNERCOMM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_APPROVEVP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_AUDIT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_AUTO_CASH: new Set(['None', 'Full']),
  TRAN_BALANCEOVERVIEW: new Set(['None', 'View']),
  TRAN_BALJRNAL: new Set(['None', 'View', 'Create', 'Full']),
  TRAN_BILLPAY_APPROVE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_BILLPAY_STATUS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_BINTRNFR: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_BINWKSHT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_BLANKORD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_BLANKORDAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_BUDGET: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_BUILD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CARDCHRG: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CARDHOLDERAUTHENTICATION: new Set(['None', 'View', 'Edit', 'Full', 'Create']),
  TRAN_CARDHOLDERAUTHEVENT: new Set(['None', 'View', 'Edit', 'Full', 'Create']),
  TRAN_CARDRFND: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CASHRFND: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CASHSALE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CHARGE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CHARGERULE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CHECK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CLEARHOLD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_COMMISSN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_COMMITPAYROLL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_COPY_BUDGET: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CREATEINVCOUNT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CUSTAUTH: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CUSTCHRG: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CUSTCRED: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CUSTDEP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CUSTINVC: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CUSTINVCAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CUSTPYMT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_CUSTRFND: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_DEPAPPL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_DEPOSIT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_EDITBANKINGINFO: new Set(['None', 'View', 'Full']),
  TRAN_EDITPROFILE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_ESTIMATE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_ESTIMATEDCOSTOVERRIDE: new Set(['None', 'Full']),
  TRAN_EXPREPT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_FFTREQ: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_FINCHRG: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_FIND: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_FORECAST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_FXREVAL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_GST_REFUND: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_IMPORTOLBFILE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_INTERCOADJ: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_INVADJST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_INVCOUNT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_INVDISTR: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_INVREVAL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_INVTRNFR: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_INVWKSHT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_ITEMRCPT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_ITEMSHIP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_JOURNAL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_JOURNALAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_LIABPYMT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_MANAGEPAYROLL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_MATCHING_RULES: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_MGRFORECAST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_NETTINGSETTLEMENTAPPRV: new Set(['None', 'Edit']),
  TRAN_NETTSTLM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_OPENBAL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_OPPRTNTY: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_ORDERRESERVATION: new Set(['None', 'View', 'Edit', 'Full', 'Create']),
  TRAN_ORDRESVAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_OWNTRNSF: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PARTNERCOMMISSN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PAYCHECK: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PAYMENTAUDIT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PAYMENTEVENT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PAYMENTRESULTPREVIEW: new Set(['None', 'View', 'Edit', 'Full', 'Create']),
  TRAN_PAYROLLRUN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PCHKJRNL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PEJRNL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_POSTPERIODS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_POSTVENDORBILLVARIANCE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PRICELIST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PRINTSHIPMENTDOCS: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PROJECT_IC_CHARGE_REQUEST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PURCHCON: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PURCHCONAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PURCHORD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PURCHORDBILL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PURCHORDRECEIVE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PURCHREQ: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_PURCHREQAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_QUOTA: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_RECOG_GIFTCERT_INCOME: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_RECONCILE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_REVARRNG: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_REVARRNGAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_REVCOMM: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_REVCOMRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_REVCONTR: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_RFQ: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_RTNAUTH: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_RTNAUTHAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_RTNAUTHCREDIT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_RTNAUTHRECEIVE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_RTNAUTHREVERSEREVCOMMIT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_SALESORD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_SALESORDAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_SALESORDCOMMITREVENUE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_SALESORDFULFILL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_SALESORDINVOICE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_SALESORDREVENUECONTRACT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_STATEMENT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_STATCHNG: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_STATUSDD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_STATUSEFT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_STATUSVP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_STPICKUP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_SYSJRNL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TAXLIAB: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TAXPYMT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TEGPYBL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TEGRCVBL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TIMEBILL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TIMECALC: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TIMEPOST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TIMER: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TRANSFER: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TRNFRORD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_TRNFRORDAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_UNBUILD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDAUTH: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDAUTHAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDAUTHCREDIT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDAUTHRETURN: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDBILL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDBILLAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDCRED: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDPYMT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDPYMTAPPRV: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VENDRFQ: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VPREPAPP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_VPREP: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WAVE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WOCLOSE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WOCOMPL: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WOISSUE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WORKORD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WORKORDBUILD: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WORKORDCLOSE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WORKORDCOMPLETE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WORKORDISSUE: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WORKORDMARKBUILT: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WORKORDMARKFIRMED: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_WORKORDMARKRELEASED: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
  TRAN_XCHGJRNL: new Set(['None', 'View']),
  TRAN_YTDADJST: new Set(['None', 'View', 'Create', 'Edit', 'Full']),
}
