#!/usr/bin/env node --experimental-modules --es-module-specifier-resolution=node --no-warnings

import argparser from './lib/argparser'

argparser({args: process.argv.slice(1), process}).catch(e => {
  console.error(e)
  process.exit(2)
})