name: Attribution NOTICES file

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup nodejs and required npm packages
      uses: actions/setup-node@v1
      with:
        node-version: 12.12

    - run: |
        npm i -g synp yarn@1.22.0
        yarn
        synp --source-file yarn.lock

    - name: ClearlyNoticed Action
      uses: dabutvin/chive-action@1.1.0
      with:
        args: --filename NOTICES
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
