name: Attribution NOTICES file

on:
  schedule:
    # every saturday on 3 am
    - cron: '0 3 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup nodejs and required npm packages
      uses: actions/setup-node@v1
      with:
        node-version: 14.15

    - run: |
        npm i -g synp yarn@1.22.0
        yarn || yarn || yarn
        synp --source-file yarn.lock

    - name: ClearlyNoticed Action
      uses: dabutvin/chive-action@1.1.0
      with:
        args: --filename NOTICES
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
